import type { TranslationKeys } from './en';
const gu: TranslationKeys = {
  appName:'TRACKMATE',logout:'લૉગ આઉટ',score:'સ્કોર',online:'ઓનલાઈન',refresh:'રિફ્રેશ',save:'સાચવો',cancel:'રદ કરો',submit:'સબમિટ કરો',close:'બંધ કરો',loading:'લોડ થઈ રહ્યું છે...',safe:'સુરક્ષિત',moderate:'મધ્યમ',restricted:'પ્રતિબંધિત',high:'ઊંચું',low:'ઓછું',medium:'મધ્યમ',critical:'ગંભીર',active:'સક્રિય',resolved:'ઉકેલાયું',acknowledged:'સ્વીકૃત',unknown:'અજ્ઞાત',language:'ભાષા',selectLanguage:'ભાષા પસંદ કરો',
  safetyScore:'સુરક્ષા સ્કોર',authorityNode:'ઓથોરિટી નોડ',navigation:'નેવિગેશન',dashboard:'ડેશબોર્ડ',incidents:'ઘટનાઓ',userManagement:'યુઝર મેનેજમેન્ટ',tourists:'પર્યટકો',residents:'રહેવાસીઓ',businesses:'વ્યવસાયો',tools:'સાધનો',dailyCheckins:'દૈનિક ચેક-ઇન',zoneManagement:'ઝોન મેનેજમેન્ટ',efirSystem:'ઈ-એફઆઈઆર સિસ્ટમ',safetyAnalytics:'સુરક્ષા વિશ્લેષણ',sendAlert:'ચેતવણી મોકલો',officer:'અધિકારી',
  map:'નકશો',trip:'પ્રવાસ',profile:'પ્રોફાઈલ',local:'સ્થાનિક',feed:'ફીડ',report:'રિપોર્ટ',intel:'માહિતી',business:'વ્યવસાય',
  login:'લૉગિન',getStarted:'શરૂ કરો',unifiedSafetyPlatform:'એકીકૃત સુરક્ષા પ્લેટફોર્મ v3',heroTitle:'રીઅલ-ટાઈમ શહેર સુરક્ષા માહિતી',heroTitleHighlight:' રહેવાસીઓ, મુલાકાતીઓ અને પ્રતિસાદ ટીમો માટે',heroDescription:'TrackMate લાઈવ નકશા, AI વિસંગતતા શોધ અને કટોકટી કાર્યપ્રવાહને જોડે છે.',enterPlatform:'પ્લેટફોર્મમાં પ્રવેશ કરો',alreadyHaveAccess:'પહેલેથી ઍક્સેસ છે',selectAccessRole:'તમારી ભૂમિકા પસંદ કરો',onePlatform:'એક પ્લેટફોર્મ, ભૂમિકા-વિશિષ્ટ કાર્યપ્રવાહ',roleDescription:'યોગ્ય સાધનો અનલૉક કરવા તમારી જવાબદારીઓ સાથે મેળ ખાતી ભૂમિકા વાપરો.',continueAs:'તરીકે ચાલુ રાખો',coreCapabilities:'મુખ્ય ક્ષમતાઓ',coreCapabilitiesDesc:'જાહેર વપરાશકર્તાઓ અને કમાન્ડ ટીમો વચ્ચે ઝડપી સંકલન માટે.',footerBrand:'TrackMate નાગરિક સુરક્ષા પ્લેટફોર્મ',footerCopyright:'© 2026 TrackMate. જોડાયેલા શહેરો માટે સંકલિત સુરક્ષા.',
  touristLabel:'પર્યટક',residentLabel:'રહેવાસી',businessLabel:'વ્યવસાય',authorityLabel:'ઓથોરિટી',touristDesc:'રીઅલ-ટાઈમ ચેતવણીઓ અને SOS સહાય સાથે આત્મવિશ્વાસથી પ્રવાસ કરો.',residentDesc:'તાત્કાલિક ઘટના રિપોર્ટિંગ સાથે તમારા પડોશનું રક્ષણ કરો.',businessDesc:'AI અને સ્માર્ટ અનુપાલન પ્રવાહનો ઉપયોગ કરી જોખમ મોનિટર કરો.',authorityDesc:'કમાન્ડ એનાલિટિક્સ અને ઈ-એફઆઈઆર સાથે સુરક્ષા ઓપરેશન સંકલિત કરો.',
  liveMonitoringGrid:'લાઈવ મોનિટરિંગ ગ્રિડ',liveMonitoringGridDesc:'ગતિવિધિ અને ઝોન જોખમ ટ્રેક કરો.',anomalyDetection:'વિસંગતતા શોધ',anomalyDetectionDesc:'AI મોડેલ અસામાન્ય પેટર્ન ઓળખે છે.',trustedIdentity:'વિશ્વસનીય ઓળખ',trustedIdentityDesc:'સુરક્ષિત ચકાસણી કાર્યપ્રવાહ યોગ્ય પ્રતિસાદકર્તાઓ ખાતરી કરે છે.',
  systemProtected:'સિસ્ટમ સુરક્ષિત — મોનિટરિંગ સક્રિય',locationMonitored:'તમારું સ્થાન મોનિટર થઈ રહ્યું છે',localAuthorities:'સ્થાનિક ઓથોરિટી',liveSafetyGIS:'લાઈવ સુરક્ષા GIS',locateMe:'મને શોધો',searchZones:'ઝોન શોધો...',activeItinerary:'સક્રિય પ્રવાસ કાર્યક્રમ',destination:'ગંતવ્ય',duration:'સમયગાળો',updatePlan:'યોજના અપડેટ કરો',verifyStay:'રોકાણ ચકાસો',noActiveTrip:'કોઈ સક્રિય પ્રવાસ નથી.',startPlanning:'આયોજન શરૂ કરો',safetyServices:'સુરક્ષા સેવાઓ',dailyCheckin:'દૈનિક ચેક-ઇન',checkedIn:'ચેક ઇન થયું ✓',reportAnomaly:'વિસંગતતા રિપોર્ટ કરો',iotSync:'IoT સિંક',safeHouse:'સેફ હાઉસ',safetyBroadcasts:'સુરક્ષા પ્રસારણ',allSectorsClear:'બધા સેક્ટર સાફ. પ્રવાસનો આનંદ માણો!',holdSOS:'3 સેકન્ડ દબાવો',alertSent:'ચેતવણી મોકલાઈ',holding:'દબાવેલું',redZoneNearby:'⚡ લાલ ઝોન નજીક',
  fetchingLocation:'સ્થાન મેળવી રહ્યું છે...',locationUpdated:'સ્થાન અપડેટ થયું',locationDenied:'સ્થાન ઍક્સેસ નકારાયું',unableGetLocation:'સ્થાન મેળવવામાં અસમર્થ',checkinFailed:'ચેક-ઇન નિષ્ફળ.',dailyCheckinRecorded:'દૈનિક ચેક-ઇન નોંધાયું ✓',checkedInAt:'ચેક ઇન થયું',verificationFailed:'ચકાસણી નિષ્ફળ',youAreIn:'✓ તમે છો',zone:'ઝોન',notInAnyZone:'ℹ કોઈ નોંધાયેલ ઝોનમાં નથી',noSafeZones:'સુરક્ષિત ઝોન નથી',nearestSafeZone:'નજીકનું સુરક્ષિત ઝોન',sosTransmissionFailed:'SOS નિષ્ફળ!',anomalyReported:'વિસંગતતા રિપોર્ટ થઈ',tripUpdated:'પ્રવાસ અપડેટ થયો',
  reportSafetyAnomaly:'સુરક્ષા વિસંગતતા રિપોર્ટ',incidentType:'ઘટના પ્રકાર',suspiciousActivity:'શંકાસ્પદ પ્રવૃત્તિ',crimeTheft:'ગુનો (ચોરી/હેરાનગતિ)',medicalEmergency:'તબીબી કટોકટી',naturalDisaster:'કુદરતી આફત',infrastructureHazard:'ઈન્ફ્રાસ્ટ્રક્ચર જોખમ',accidentOther:'અકસ્માત / અન્ય',title:'શીર્ષક',briefSummary:'ટૂંકસાર',description:'વર્ણન',detailsPlaceholder:'વિગતો...',severity:'ગંભીરતા',autoDetected:'સ્વતઃ-શોધ',submitReport:'રિપોર્ટ સબમિટ કરો',
  updateTravelPlan:'પ્રવાસ યોજના અપડેટ',destinationRegion:'ગંતવ્ય પ્રદેશ',destinationPlaceholder:'દા.ત. તવાંગ જિલ્લો',startDate:'શરૂઆતની તારીખ',endDate:'સમાપ્તિ તારીખ',saveChanges:'ફેરફારો સાચવો',
  iotDeviceSync:'IoT ડિવાઇસ સિંક',bluetoothPair:'બ્લૂટૂથ પેર',searchBluetooth:'નજીકના IoT બેન્ડ શોધો',searchingBluetooth:'બ્લૂટૂથ શોધી રહ્યું છે...',wifiDirect:'વાઈફાઈ ડાયરેક્ટ',connectViaNetwork:'સ્થાનિક નેટવર્ક દ્વારા કનેક્ટ',wifiScanInitiated:'વાઈફાઈ સ્કેન શરૂ',
  noWardAssigned:'તમારા ખાતામાં કોઈ વોર્ડ નથી.',yourArea:'તમારો વિસ્તાર',liveMonitoring:'લાઈવ મોનિટરિંગ',generalMonitoring:'સામાન્ય મોનિટરિંગ · બધા વિસ્તારો',healthy:'સ્વસ્થ',activeCircle:'સક્રિય સર્કલ',holdForEmergency:'કટોકટી માટે દબાવો',holdFor3Seconds:'મદદ મોકલવા 3 સેકન્ડ દબાવો',releaseToCancel:'SOS રદ કરવા છોડો',helpDispatched:'મદદ મોકલાઈ',authoritiesNotified:'અધિકારીઓને જાણ કરાઈ.',recentIncidents:'તાજેતરની ઘટનાઓ',viewMap:'નકશો જુઓ',noDescription:'વર્ણન નથી.',wardClear:'વોર્ડ સાફ છે.',communityVitals:'સમુદાય સ્થિતિ',policePatrol:'પોલીસ ગસ્ત',communityVerified:'સમુદાય ચકાસેલ',streetLight:'સ્ટ્રીટ લાઈટ કવરેજ',statusOperational:'સ્થિતિ: ચાલુ',checkinDue:'ચેક-ઇન બાકી',loadingWardData:'વોર્ડ ડેટા લોડ થઈ રહ્યો છે...',
  zoneSafetyStatus:'ઝોન સુરક્ષા સ્થિતિ',businessZone:'વ્યાપાર ઝોન',dynamicScore:'ગતિશીલ સ્કોર',footfallOverview:'ફૂટફોલ ઓવરવ્યૂ',realTimeTraffic:'રીઅલ-ટાઈમ ટ્રાફિક',activeVisitors:'સક્રિય મુલાકાતીઓ',nearbyTourists:'નજીકના પર્યટકો',radius200m:'200 મી. ત્રિજ્યા',verifiedTouristsInVicinity:'ચકાસેલ પર્યટકો નજીકમાં',safetyAdvisories:'સુરક્ષા સલાહ',postAdvisory:'સલાહ પોસ્ટ કરો',noAdvisoryDetails:'સલાહ વિગતો નથી.',noActiveAdvisories:'સક્રિય સલાહ નથી.',blockchainIdentityProof:'બ્લોકચેઈન ઓળખ પ્રમાણ',validateCredentials:'Trackmate લેજર સામે પ્રમાણપત્રો ચકાસો.',verify:'ચકાસો',ledgerVerified:'લેજર ચકાસેલ',authValid:'પ્રમાણીકરણ માન્ય',securityClearance:'સુરક્ષા મંજૂરી ચકાસેલ',verification:'ચકાસણી',identityProofed:'ઓળખ પ્રમાણિત',pending:'પેન્ડિંગ',role:'ભૂમિકા',identityNotFound:'લેજરમાં ઓળખ નથી.',verificationUnavailable:'ચકાસણી સેવા અનુપલબ્ધ.',
  holdForBusinessSOS:'વ્યાપાર SOS દબાવો',holdFor3SecondsTrigger:'રેડ અલાર્મ 3 સેકન્ડ દબાવો',releaseToCancel2:'SOS રદ કરો',sosDispatched:'SOS અધિકારીઓને મોકલાયું',authorityReceived:'ઓથોરિટી પેનલે ટ્રિગર રીઅલ ટાઈમમાં મેળવ્યું.',loadingBusinessData:'વ્યાપાર ડેટા લોડ...',
  commandDashboard:'કમાન્ડ ડેશબોર્ડ',authorityOfficer:'ઓથોરિટી અધિકારી',liveUsers:'લાઈવ યુઝર્સ',openIncidents:'ખુલ્લી ઘટનાઓ',sosLastHour:'SOS (છેલ્લો કલાક)',totalProfiles:'કુલ પ્રોફાઈલ',needsAttention:'ધ્યાન જરૂરી',liveTrackingActive:'લાઈવ ટ્રેકિંગ સક્રિય',authorityCommandMap:'ઓથોરિટી કમાન્ડ લાઈવ મેપ',trackingDevices:'ટ્રેકિંગ',liveDevicesAcrossZones:'લાઈવ ડિવાઈસ ઝોનમાં.',resetView:'વ્યૂ રીસેટ',focusLive:'લાઈવ ફોકસ',drawZone:'ઝોન દોરો',mapLegend:'મેપ લેજન્ડ',safeZone:'સુરક્ષિત ઝોન',moderateZone:'મધ્યમ ઝોન',highRisk:'ઊંચું જોખમ',restrictedZone:'પ્રતિબંધિત ઝોન',tourist:'પર્યટક',resident:'રહેવાસી',clearUserFilter:'ફિલ્ટર દૂર કરો ✕',
  checkinToday:'આજ',touristCheckins24h:'છેલ્લા 24 કલાકના ચેક-ઇન',noCheckins24h:'24 કલાકમાં ચેક-ઇન નથી.',locationCheckin:'સ્થાન ચેક-ઇન',checkedInStatus:'ચેક ઇન થયું',liveAlertFeed:'લાઈવ ચેતવણી ફીડ',clickRowToIsolate:'મેપ પર રિપોર્ટર અલગ કરવા ક્લિક કરો',connectingToFeed:'ફીડ કનેક્ટ થઈ રહી છે...',severityCol:'ગંભીરતા',titleZone:'શીર્ષક / ઝોન',reporter:'રિપોર્ટર',status:'સ્થિતિ',actions:'ક્રિયાઓ',unknownLocation:'અજ્ઞાત સ્થાન',system:'સિસ્ટમ',acknowledge:'સ્વીકારો',resolve:'ઉકેલો',done:'✓ થયું',noActiveIncidents:'સક્રિય ઘટનાઓ નથી.',redAlert:'રેડ અલર્ટ',personInDanger:'જોખમમાં વ્યક્તિ',unknownUser:'અજ્ઞાત યુઝર',realDanger:'વાસ્તવિક જોખમ',falseAlarm:'ખોટો અલાર્મ',confidence:'વિશ્વાસ',trackLocation:'સ્થાન ટ્રેક કરો',zoneAdded:'ઝોન ઉમેરાયું.',zoneDeleted:'ઝોન દૂર થયું.',failedUpdateIncident:'ઘટના અપડેટ નિષ્ફળ.',failedSaveZone:'ઝોન સાચવવું નિષ્ફળ',failedDeleteZone:'ઝોન દૂર કરવું નિષ્ફળ.',deleteZoneConfirm:'આ ઝોન દૂર કરવું?',reporterLocationUnavailable:'રિપોર્ટરનું સ્થાન અનુપલબ્ધ.',searchZonesPlaceholder:'ઝોન શોધો...',
};
export default gu;
