import type { TranslationKeys } from './en';
const kn: Partial<TranslationKeys> = {
  appName:'TRACKMATE',logout:'ಲಾಗ್ ಔಟ್',score:'ಅಂಕ',online:'ಆನ್‌ಲೈನ್',refresh:'ರಿಫ್ರೆಶ್',save:'ಉಳಿಸಿ',cancel:'ರದ್ದು',submit:'ಸಲ್ಲಿಸಿ',close:'ಮುಚ್ಚಿ',loading:'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',safe:'ಸುರಕ್ಷಿತ',moderate:'ಮಧ್ಯಮ',restricted:'ನಿಷೇಧಿತ',high:'ಹೆಚ್ಚಿನ',low:'ಕಡಿಮೆ',medium:'ಮಧ್ಯಮ',critical:'ತೀವ್ರ',active:'ಸಕ್ರಿಯ',resolved:'ಪರಿಹರಿಸಲಾಗಿದೆ',acknowledged:'ಅಂಗೀಕರಿಸಲಾಗಿದೆ',unknown:'ಅಪರಿಚಿತ',language:'ಭಾಷೆ',selectLanguage:'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
  safetyScore:'ಸುರಕ್ಷತಾ ಅಂಕ',authorityNode:'ಅಧಿಕಾರ ನೋಡ್',navigation:'ನ್ಯಾವಿಗೇಶನ್',dashboard:'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',incidents:'ಘಟನೆಗಳು',userManagement:'ಬಳಕೆದಾರ ನಿರ್ವಹಣೆ',tourists:'ಪ್ರವಾಸಿಗರು',residents:'ನಿವಾಸಿಗಳು',businesses:'ವ್ಯಾಪಾರಗಳು',tools:'ಉಪಕರಣಗಳು',dailyCheckins:'ದೈನಿಕ ಚೆಕ್-ಇನ್',zoneManagement:'ವಲಯ ನಿರ್ವಹಣೆ',efirSystem:'ಇ-ಎಫ್‌ಐಆರ್ ವ್ಯವಸ್ಥೆ',safetyAnalytics:'ಸುರಕ್ಷತಾ ವಿಶ್ಲೇಷಣೆ',sendAlert:'ಎಚ್ಚರಿಕೆ ಕಳುಹಿಸಿ',officer:'ಅಧಿಕಾರಿ',
  map:'ನಕ್ಷೆ',trip:'ಪ್ರವಾಸ',profile:'ಪ್ರೊಫೈಲ್',local:'ಸ್ಥಳೀಯ',feed:'ಫೀಡ್',report:'ವರದಿ',intel:'ಮಾಹಿತಿ',business:'ವ್ಯಾಪಾರ',
  login:'ಲಾಗಿನ್',getStarted:'ಪ್ರಾರಂಭಿಸಿ',unifiedSafetyPlatform:'ಏಕೀಕೃತ ಸುರಕ್ಷತಾ ವೇದಿಕೆ v3',heroTitle:'ರಿಯಲ್-ಟೈಮ್ ನಗರ ಸುರಕ್ಷತಾ ಮಾಹಿತಿ',heroTitleHighlight:' ನಿವಾಸಿಗಳು, ಸಂದರ್ಶಕರು ಮತ್ತು ಪ್ರತಿಕ್ರಿಯೆ ತಂಡಗಳಿಗೆ',heroDescription:'TrackMate ಲೈವ್ ನಕ್ಷೆಗಳು, AI ಅಸಮಾನತೆ ಪತ್ತೆ ಮತ್ತು ತುರ್ತು ಕಾರ್ಯಪ್ರವಾಹವನ್ನು ಸಂಪರ್ಕಿಸುತ್ತದೆ.',enterPlatform:'ವೇದಿಕೆಗೆ ಪ್ರವೇಶಿಸಿ',alreadyHaveAccess:'ಈಗಾಗಲೇ ಪ್ರವೇಶ ಇದೆ',selectAccessRole:'ನಿಮ್ಮ ಪಾತ್ರ ಆಯ್ಕೆಮಾಡಿ',onePlatform:'ಒಂದು ವೇದಿಕೆ, ಪಾತ್ರ-ನಿರ್ದಿಷ್ಟ ಕಾರ್ಯಪ್ರವಾಹ',roleDescription:'ಸರಿಯಾದ ಉಪಕರಣಗಳನ್ನು ಅನ್‌ಲಾಕ್ ಮಾಡಲು ನಿಮ್ಮ ಜವಾಬ್ದಾರಿಗಳಿಗೆ ಹೊಂದುವ ಪಾತ್ರ ಬಳಸಿ.',continueAs:'ಆಗಿ ಮುಂದುವರಿಸಿ',coreCapabilities:'ಮುಖ್ಯ ಸಾಮರ್ಥ್ಯಗಳು',coreCapabilitiesDesc:'ಸಾರ್ವಜನಿಕ ಬಳಕೆದಾರರು ಮತ್ತು ಕಮಾಂಡ್ ತಂಡಗಳ ನಡುವೆ ತ್ವರಿತ ಸಮನ್ವಯ.',footerBrand:'TrackMate ನಾಗರಿಕ ಸುರಕ್ಷತಾ ವೇದಿಕೆ',footerCopyright:'© 2026 TrackMate. ಸಂಪರ್ಕಿತ ನಗರಗಳಿಗೆ ಸಮನ್ವಯ ಸುರಕ್ಷತೆ.',
  touristLabel:'ಪ್ರವಾಸಿ',residentLabel:'ನಿವಾಸಿ',businessLabel:'ವ್ಯಾಪಾರ',authorityLabel:'ಅಧಿಕಾರ',touristDesc:'ರಿಯಲ್-ಟೈಮ್ ಎಚ್ಚರಿಕೆಗಳು ಮತ್ತು SOS ಬೆಂಬಲದೊಂದಿಗೆ ಆತ್ಮವಿಶ್ವಾಸದಿಂದ ಪ್ರಯಾಣಿಸಿ.',residentDesc:'ತಕ್ಷಣ ಘಟನೆ ವರದಿ ಮಾಡುವ ಮೂಲಕ ನಿಮ್ಮ ನೆರೆಹೊರೆಯನ್ನು ರಕ್ಷಿಸಿ.',businessDesc:'AI ಬಳಸಿ ನಿಮ್ಮ ಆಸ್ತಿ ಸುತ್ತಲಿನ ಅಪಾಯವನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಿ.',authorityDesc:'ಕಮಾಂಡ್ ವಿಶ್ಲೇಷಣೆ ಮತ್ತು ಇ-ಎಫ್‌ಐಆರ್ ಮೂಲಕ ನಗರ ಸುರಕ್ಷತಾ ಕಾರ್ಯಾಚರಣೆಗಳನ್ನು ಸಮನ್ವಯಗೊಳಿಸಿ.',
  liveMonitoringGrid:'ಲೈವ್ ಮಾನಿಟರಿಂಗ್ ಗ್ರಿಡ್',liveMonitoringGridDesc:'ಚಲನೆ ಮತ್ತು ವಲಯ ಅಪಾಯವನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ.',anomalyDetection:'ಅಸಮಾನತೆ ಪತ್ತೆ',anomalyDetectionDesc:'AI ಮಾದರಿಗಳು ಅಸಾಮಾನ್ಯ ಮಾದರಿಗಳನ್ನು ಗುರುತಿಸುತ್ತವೆ.',trustedIdentity:'ವಿಶ್ವಾಸಾರ್ಹ ಗುರುತು',trustedIdentityDesc:'ಸುರಕ್ಷಿತ ಪರಿಶೀಲನೆ ಕಾರ್ಯಪ್ರವಾಹ ಸರಿಯಾದ ಪ್ರತಿಕ್ರಿಯಿಸುವವರನ್ನು ಖಚಿತಪಡಿಸುತ್ತದೆ.',
  systemProtected:'ವ್ಯವಸ್ಥೆ ರಕ್ಷಿತ — ಮೇಲ್ವಿಚಾರಣೆ ಸಕ್ರಿಯ',locationMonitored:'ನಿಮ್ಮ ಸ್ಥಳ ಮೇಲ್ವಿಚಾರಣೆಯಲ್ಲಿದೆ',localAuthorities:'ಸ್ಥಳೀಯ ಅಧಿಕಾರಿಗಳು',liveSafetyGIS:'ಲೈವ್ ಸುರಕ್ಷತಾ GIS',locateMe:'ನನ್ನನ್ನು ಹುಡುಕಿ',searchZones:'ವಲಯಗಳನ್ನು ಹುಡುಕಿ...',activeItinerary:'ಸಕ್ರಿಯ ಪ್ರವಾಸ ಕಾರ್ಯಕ್ರಮ',destination:'ಗಮ್ಯಸ್ಥಾನ',duration:'ಅವಧಿ',updatePlan:'ಯೋಜನೆ ನವೀಕರಿಸಿ',verifyStay:'ತಂಗುವಿಕೆ ಪರಿಶೀಲಿಸಿ',noActiveTrip:'ಸಕ್ರಿಯ ಪ್ರವಾಸ ಇಲ್ಲ.',startPlanning:'ಯೋಜನೆ ಪ್ರಾರಂಭಿಸಿ',safetyServices:'ಸುರಕ್ಷತಾ ಸೇವೆಗಳು',dailyCheckin:'ದೈನಿಕ ಚೆಕ್-ಇನ್',checkedIn:'ಚೆಕ್ ಇನ್ ಆಯಿತು ✓',reportAnomaly:'ಅಸಮಾನತೆ ವರದಿ ಮಾಡಿ',iotSync:'IoT ಸಿಂಕ್',safeHouse:'ಸೇಫ್ ಹೌಸ್',safetyBroadcasts:'ಸುರಕ್ಷತಾ ಪ್ರಸಾರಗಳು',allSectorsClear:'ಎಲ್ಲಾ ವಲಯಗಳು ಸ್ಪಷ್ಟ. ಪ್ರವಾಸ ಆನಂದಿಸಿ!',holdSOS:'3 ಸೆಕೆಂಡ್ ಒತ್ತಿ',alertSent:'ಎಚ್ಚರಿಕೆ ಕಳುಹಿಸಲಾಯಿತು',holding:'ಒತ್ತಲಾಗುತ್ತಿದೆ',redZoneNearby:'⚡ ಕೆಂಪು ವಲಯ ಹತ್ತಿರ',
  fetchingLocation:'ಸ್ಥಳ ಪಡೆಯಲಾಗುತ್ತಿದೆ...',locationUpdated:'ಸ್ಥಳ ನವೀಕರಿಸಲಾಯಿತು',locationDenied:'ಸ್ಥಳ ಪ್ರವೇಶ ನಿರಾಕರಿಸಲಾಯಿತು',unableGetLocation:'ಸ್ಥಳ ಪಡೆಯಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ',checkinFailed:'ಚೆಕ್-ಇನ್ ವಿಫಲ.',dailyCheckinRecorded:'ಚೆಕ್-ಇನ್ ದಾಖಲಾಯಿತು ✓',checkedInAt:'ಚೆಕ್ ಇನ್ ಆಯಿತು',verificationFailed:'ಪರಿಶೀಲನೆ ವಿಫಲ',youAreIn:'✓ ನೀವು ಇದ್ದೀರಿ',zone:'ವಲಯ',notInAnyZone:'ℹ ಯಾವುದೇ ನೋಂದಾಯಿತ ವಲಯದಲ್ಲಿ ಇಲ್ಲ',noSafeZones:'ಸುರಕ್ಷಿತ ವಲಯಗಳಿಲ್ಲ',nearestSafeZone:'ಹತ್ತಿರದ ಸುರಕ್ಷಿತ ವಲಯ',sosTransmissionFailed:'SOS ವಿಫಲ!',anomalyReported:'ಅಸಮಾನತೆ ವರದಿಯಾಯಿತು',tripUpdated:'ಪ್ರವಾಸ ನವೀಕರಿಸಲಾಯಿತು',
  reportSafetyAnomaly:'ಸುರಕ್ಷತಾ ಅಸಮಾನತೆ ವರದಿ',incidentType:'ಘಟನೆ ಪ್ರಕಾರ',suspiciousActivity:'ಅನುಮಾನಾಸ್ಪದ ಚಟುವಟಿಕೆ',crimeTheft:'ಅಪರಾಧ (ಕಳ್ಳತನ/ಕಿರುಕುಳ)',medicalEmergency:'ವೈದ್ಯಕೀಯ ತುರ್ತು',naturalDisaster:'ನೈಸರ್ಗಿಕ ವಿಪತ್ತು',infrastructureHazard:'ಮೂಲಸೌಕರ್ಯ ಅಪಾಯ',accidentOther:'ಅಪಘಾತ / ಇತರ',title:'ಶೀರ್ಷಿಕೆ',briefSummary:'ಸಂಕ್ಷಿಪ್ತ ಸಾರಾಂಶ',description:'ವಿವರಣೆ',detailsPlaceholder:'ವಿವರಗಳು...',severity:'ತೀವ್ರತೆ',autoDetected:'ಸ್ವಯಂ-ಪತ್ತೆ',submitReport:'ವರದಿ ಸಲ್ಲಿಸಿ',
  updateTravelPlan:'ಪ್ರವಾಸ ಯೋಜನೆ ನವೀಕರಣ',destinationRegion:'ಗಮ್ಯಸ್ಥಾನ ಪ್ರದೇಶ',destinationPlaceholder:'ಉದಾ. ತವಾಂಗ್ ಜಿಲ್ಲೆ',startDate:'ಪ್ರಾರಂಭ ದಿನಾಂಕ',endDate:'ಅಂತಿಮ ದಿನಾಂಕ',saveChanges:'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
  iotDeviceSync:'IoT ಸಾಧನ ಸಿಂಕ್',bluetoothPair:'ಬ್ಲೂಟೂತ್ ಜೋಡಿ',searchBluetooth:'ಹತ್ತಿರದ IoT ಬ್ಯಾಂಡ್ ಹುಡುಕಿ',searchingBluetooth:'ಬ್ಲೂಟೂತ್ ಹುಡುಕುತ್ತಿದೆ...',wifiDirect:'ವೈಫೈ ಡೈರೆಕ್ಟ್',connectViaNetwork:'ಸ್ಥಳೀಯ ನೆಟ್‌ವರ್ಕ್ ಮೂಲಕ ಸಂಪರ್ಕಿಸಿ',wifiScanInitiated:'ವೈಫೈ ಸ್ಕ್ಯಾನ್ ಪ್ರಾರಂಭ',
  noWardAssigned:'ನಿಮ್ಮ ಖಾತೆಗೆ ವಾರ್ಡ್ ಇಲ್ಲ.',yourArea:'ನಿಮ್ಮ ಪ್ರದೇಶ',liveMonitoring:'ಲೈವ್ ಮೇಲ್ವಿಚಾರಣೆ',generalMonitoring:'ಸಾಮಾನ್ಯ ಮೇಲ್ವಿಚಾರಣೆ · ಎಲ್ಲಾ ಪ್ರದೇಶಗಳು',healthy:'ಆರೋಗ್ಯಕರ',activeCircle:'ಸಕ್ರಿಯ ವೃತ್ತ',holdForEmergency:'ತುರ್ತಿಗೆ ಒತ್ತಿ',holdFor3Seconds:'ಸಹಾಯ ಕಳುಹಿಸಲು 3 ಸೆಕೆಂಡ್ ಒತ್ತಿ',releaseToCancel:'SOS ರದ್ದು ಮಾಡಲು ಬಿಡಿ',helpDispatched:'ಸಹಾಯ ಕಳುಹಿಸಲಾಯಿತು',authoritiesNotified:'ಅಧಿಕಾರಿಗಳಿಗೆ ತಿಳಿಸಲಾಯಿತು.',recentIncidents:'ಇತ್ತೀಚಿನ ಘಟನೆಗಳು',viewMap:'ನಕ್ಷೆ ನೋಡಿ',noDescription:'ವಿವರಣೆ ಇಲ್ಲ.',wardClear:'ವಾರ್ಡ್ ಸ್ಪಷ್ಟ.',communityVitals:'ಸಮುದಾಯ ಸ್ಥಿತಿ',policePatrol:'ಪೊಲೀಸ್ ಗಸ್ತು',communityVerified:'ಸಮುದಾಯ ಪರಿಶೀಲಿತ',streetLight:'ಬೀದಿ ದೀಪ ಕವರೇಜ್',statusOperational:'ಸ್ಥಿತಿ: ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತಿದೆ',checkinDue:'ಚೆಕ್-ಇನ್ ಬಾಕಿ',loadingWardData:'ವಾರ್ಡ್ ಡೇಟಾ ಲೋಡ್...',
  zoneSafetyStatus:'ವಲಯ ಸುರಕ್ಷತಾ ಸ್ಥಿತಿ',businessZone:'ವ್ಯಾಪಾರ ವಲಯ',dynamicScore:'ಡೈನಾಮಿಕ್ ಅಂಕ',footfallOverview:'ಪಾದಚಾರಿ ಅವಲೋಕನ',realTimeTraffic:'ರಿಯಲ್-ಟೈಮ್ ಟ್ರಾಫಿಕ್',activeVisitors:'ಸಕ್ರಿಯ ಸಂದರ್ಶಕರು',nearbyTourists:'ಹತ್ತಿರದ ಪ್ರವಾಸಿಗರು',radius200m:'200 ಮೀ ತ್ರಿಜ್ಯ',verifiedTouristsInVicinity:'ಪರಿಶೀಲಿತ ಪ್ರವಾಸಿಗರು ಹತ್ತಿರ',safetyAdvisories:'ಸುರಕ್ಷತಾ ಸಲಹೆಗಳು',postAdvisory:'ಸಲಹೆ ಪೋಸ್ಟ್',noAdvisoryDetails:'ಸಲಹೆ ವಿವರಗಳಿಲ್ಲ.',noActiveAdvisories:'ಸಕ್ರಿಯ ಸಲಹೆಗಳಿಲ್ಲ.',blockchainIdentityProof:'ಬ್ಲಾಕ್‌ಚೈನ್ ಗುರುತಿನ ಪುರಾವೆ',validateCredentials:'Trackmate ಲೆಡ್ಜರ್ ವಿರುದ್ಧ ಪರಿಶೀಲಿಸಿ.',verify:'ಪರಿಶೀಲಿಸಿ',ledgerVerified:'ಲೆಡ್ಜರ್ ಪರಿಶೀಲಿತ',authValid:'ದೃಢೀಕರಣ ಮಾನ್ಯ',securityClearance:'ಭದ್ರತಾ ಅನುಮತಿ ಪರಿಶೀಲಿತ',verification:'ಪರಿಶೀಲನೆ',identityProofed:'ಗುರುತು ಸಾಬೀತಾಗಿದೆ',pending:'ಬಾಕಿ',role:'ಪಾತ್ರ',identityNotFound:'ಲೆಡ್ಜರ್‌ನಲ್ಲಿ ಗುರುತು ಇಲ್ಲ.',verificationUnavailable:'ಪರಿಶೀಲನೆ ಸೇವೆ ಲಭ್ಯವಿಲ್ಲ.',
  holdForBusinessSOS:'ವ್ಯಾಪಾರ SOS ಒತ್ತಿ',holdFor3SecondsTrigger:'ರೆಡ್ ಅಲಾರ್ಮ್ 3 ಸೆಕೆಂಡ್ ಒತ್ತಿ',releaseToCancel2:'SOS ರದ್ದು',sosDispatched:'SOS ಅಧಿಕಾರಿಗಳಿಗೆ ಕಳುಹಿಸಲಾಯಿತು',authorityReceived:'ಅಧಿಕಾರ ಪ್ಯಾನೆಲ್ ರಿಯಲ್ ಟೈಮ್‌ನಲ್ಲಿ ಸ್ವೀಕರಿಸಿತು.',loadingBusinessData:'ವ್ಯಾಪಾರ ಡೇಟಾ ಲೋಡ್...',
  commandDashboard:'ಕಮಾಂಡ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',authorityOfficer:'ಅಧಿಕಾರ ಅಧಿಕಾರಿ',liveUsers:'ಲೈವ್ ಬಳಕೆದಾರರು',openIncidents:'ತೆರೆದ ಘಟನೆಗಳು',sosLastHour:'SOS (ಕೊನೆಯ ಗಂಟೆ)',totalProfiles:'ಒಟ್ಟು ಪ್ರೊಫೈಲ್‌ಗಳು',needsAttention:'ಗಮನ ಅಗತ್ಯ',liveTrackingActive:'ಲೈವ್ ಟ್ರ್ಯಾಕಿಂಗ್ ಸಕ್ರಿಯ',authorityCommandMap:'ಅಧಿಕಾರ ಕಮಾಂಡ್ ಲೈವ್ ನಕ್ಷೆ',trackingDevices:'ಟ್ರ್ಯಾಕಿಂಗ್',liveDevicesAcrossZones:'ಲೈವ್ ಸಾಧನಗಳು ವಲಯಗಳಲ್ಲಿ.',resetView:'ವೀಕ್ಷಣೆ ಮರುಹೊಂದಿಸಿ',focusLive:'ಲೈವ್ ಫೋಕಸ್',drawZone:'ವಲಯ ರಚಿಸಿ',mapLegend:'ನಕ್ಷೆ ಸಂಕೇತ',safeZone:'ಸುರಕ್ಷಿತ ವಲಯ',moderateZone:'ಮಧ್ಯಮ ವಲಯ',highRisk:'ಹೆಚ್ಚಿನ ಅಪಾಯ',restrictedZone:'ನಿಷೇಧಿತ ವಲಯ',tourist:'ಪ್ರವಾಸಿ',resident:'ನಿವಾಸಿ',clearUserFilter:'ಫಿಲ್ಟರ್ ತೆಗೆ ✕',
  checkinToday:'ಇಂದು',touristCheckins24h:'ಕಳೆದ 24 ಗಂಟೆ ಚೆಕ್-ಇನ್‌ಗಳು',noCheckins24h:'24 ಗಂಟೆಯಲ್ಲಿ ಚೆಕ್-ಇನ್ ಇಲ್ಲ.',locationCheckin:'ಸ್ಥಳ ಚೆಕ್-ಇನ್',checkedInStatus:'ಚೆಕ್ ಇನ್ ಆಯಿತು',liveAlertFeed:'ಲೈವ್ ಎಚ್ಚರಿಕೆ ಫೀಡ್',clickRowToIsolate:'ನಕ್ಷೆಯಲ್ಲಿ ವರದಿಗಾರನನ್ನು ಪ್ರತ್ಯೇಕಿಸಲು ಕ್ಲಿಕ್ ಮಾಡಿ',connectingToFeed:'ಫೀಡ್‌ಗೆ ಸಂಪರ್ಕಿಸುತ್ತಿದೆ...',severityCol:'ತೀವ್ರತೆ',titleZone:'ಶೀರ್ಷಿಕೆ / ವಲಯ',reporter:'ವರದಿಗಾರ',status:'ಸ್ಥಿತಿ',actions:'ಕ್ರಮಗಳು',unknownLocation:'ಅಪರಿಚಿತ ಸ್ಥಳ',system:'ವ್ಯವಸ್ಥೆ',acknowledge:'ಅಂಗೀಕರಿಸಿ',resolve:'ಪರಿಹರಿಸಿ',done:'✓ ಮುಗಿದಿದೆ',noActiveIncidents:'ಸಕ್ರಿಯ ಘಟನೆಗಳಿಲ್ಲ.',redAlert:'ರೆಡ್ ಅಲರ್ಟ್',personInDanger:'ಅಪಾಯದಲ್ಲಿ ವ್ಯಕ್ತಿ',unknownUser:'ಅಪರಿಚಿತ ಬಳಕೆದಾರ',realDanger:'ನಿಜವಾದ ಅಪಾಯ',falseAlarm:'ತಪ್ಪು ಅಲಾರ್ಮ್',confidence:'ವಿಶ್ವಾಸ',trackLocation:'ಸ್ಥಳ ಟ್ರ್ಯಾಕ್',zoneAdded:'ವಲಯ ಸೇರಿಸಲಾಯಿತು.',zoneDeleted:'ವಲಯ ಅಳಿಸಲಾಯಿತು.',failedUpdateIncident:'ಘಟನೆ ನವೀಕರಣ ವಿಫಲ.',failedSaveZone:'ವಲಯ ಉಳಿಸುವುದು ವಿಫಲ',failedDeleteZone:'ವಲಯ ಅಳಿಸುವುದು ವಿಫಲ.',deleteZoneConfirm:'ಈ ವಲಯ ಅಳಿಸುವುದೇ?',reporterLocationUnavailable:'ವರದಿಗಾರನ ಸ್ಥಳ ಲಭ್ಯವಿಲ್ಲ.',searchZonesPlaceholder:'ವಲಯಗಳನ್ನು ಹುಡುಕಿ...',
};
export default kn;
