import type { TranslationKeys } from './en';
const mr: Partial<TranslationKeys> = {
  appName:'TRACKMATE',logout:'लॉग आउट',score:'गुण',online:'ऑनलाइन',refresh:'रिफ्रेश',save:'जतन करा',cancel:'रद्द करा',submit:'सबमिट करा',close:'बंद करा',loading:'लोड होत आहे...',safe:'सुरक्षित',moderate:'मध्यम',restricted:'प्रतिबंधित',high:'उच्च',low:'कमी',medium:'मध्यम',critical:'गंभीर',active:'सक्रिय',resolved:'निराकरण केले',acknowledged:'मान्य केले',unknown:'अज्ञात',language:'भाषा',selectLanguage:'भाषा निवडा',
  safetyScore:'सुरक्षा गुण',authorityNode:'प्राधिकरण नोड',navigation:'नेव्हिगेशन',dashboard:'डॅशबोर्ड',incidents:'घटना',userManagement:'वापरकर्ता व्यवस्थापन',tourists:'पर्यटक',residents:'रहिवासी',businesses:'व्यवसाय',tools:'साधने',dailyCheckins:'दैनिक चेक-इन',zoneManagement:'झोन व्यवस्थापन',efirSystem:'ई-एफआयआर प्रणाली',safetyAnalytics:'सुरक्षा विश्लेषण',sendAlert:'सतर्कता पाठवा',officer:'अधिकारी',
  map:'नकाशा',trip:'सहल',profile:'प्रोफाइल',local:'स्थानिक',feed:'फीड',report:'अहवाल',intel:'माहिती',business:'व्यवसाय',
  login:'लॉगिन',getStarted:'सुरू करा',unifiedSafetyPlatform:'एकात्मिक सुरक्षा प्लॅटफॉर्म v3',heroTitle:'रिअल-टाइम शहर सुरक्षा माहिती',heroTitleHighlight:' रहिवासी, अभ्यागत आणि प्रतिसाद पथकांसाठी',heroDescription:'TrackMate लाइव्ह नकाशे, AI विसंगती शोध, सुरक्षित ओळख एकत्रित करते.',enterPlatform:'प्लॅटफॉर्ममध्ये प्रवेश करा',alreadyHaveAccess:'आधीच प्रवेश आहे',selectAccessRole:'तुमची भूमिका निवडा',onePlatform:'एक प्लॅटफॉर्म, भूमिका-विशिष्ट कार्यप्रवाह',roleDescription:'योग्य साधने अनलॉक करण्यासाठी तुमच्या जबाबदाऱ्यांशी जुळणारी भूमिका वापरा.',continueAs:'म्हणून सुरू ठेवा',coreCapabilities:'मुख्य क्षमता',coreCapabilitiesDesc:'सार्वजनिक वापरकर्ते आणि कमांड पथकांमध्ये जलद समन्वयासाठी.',footerBrand:'TrackMate नागरिक सुरक्षा प्लॅटफॉर्म',footerCopyright:'© 2026 TrackMate. कनेक्टेड शहरांसाठी समन्वित सुरक्षा.',
  touristLabel:'पर्यटक',residentLabel:'रहिवासी',businessLabel:'व्यवसाय',authorityLabel:'प्राधिकरण',touristDesc:'रिअल-टाइम सतर्कता आणि SOS समर्थनासह आत्मविश्वासाने प्रवास करा.',residentDesc:'त्वरित घटना अहवाल आणि सत्यापित स्थानिक अपडेट्ससह तुमच्या शेजारचे रक्षण करा.',businessDesc:'भविष्यसूचक AI वापरून तुमच्या मालमत्तेभोवती जोखीम निरीक्षण करा.',authorityDesc:'कमांड विश्लेषण आणि ई-एफआयआर सह शहरव्यापी सुरक्षा ऑपरेशन समन्वय करा.',
  liveMonitoringGrid:'लाइव्ह मॉनिटरिंग ग्रिड',liveMonitoringGridDesc:'एकात्मिक लेयर द्वारे हालचाल आणि झोन जोखीम ट्रॅक करा.',anomalyDetection:'विसंगती शोध',anomalyDetectionDesc:'AI मॉडेल असामान्य नमुने ओळखतात.',trustedIdentity:'विश्वासार्ह ओळख',trustedIdentityDesc:'सुरक्षित सत्यापन कार्यप्रवाह योग्य प्रतिसादकर्ते घटनांवर कारवाई करतात.',
  systemProtected:'सिस्टम सुरक्षित — निरीक्षण सक्रिय',locationMonitored:'तुमचे स्थान निरीक्षणात आहे',localAuthorities:'स्थानिक प्राधिकरण',liveSafetyGIS:'लाइव्ह सुरक्षा GIS',locateMe:'मला शोधा',searchZones:'झोन शोधा...',activeItinerary:'सक्रिय प्रवास कार्यक्रम',destination:'गंतव्य',duration:'कालावधी',updatePlan:'योजना अपडेट करा',verifyStay:'मुक्काम सत्यापित करा',noActiveTrip:'कोणताही सक्रिय प्रवास नाही.',startPlanning:'नियोजन सुरू करा',safetyServices:'सुरक्षा सेवा',dailyCheckin:'दैनिक चेक-इन',checkedIn:'चेक इन झाले ✓',reportAnomaly:'विसंगती अहवाल द्या',iotSync:'IoT सिंक',safeHouse:'सेफ हाउस',safetyBroadcasts:'सुरक्षा प्रसारण',allSectorsClear:'सर्व क्षेत्रे स्वच्छ. सहलीचा आनंद घ्या!',holdSOS:'3 सेकंद दाबा',alertSent:'सतर्कता पाठवली',holding:'दाबत आहे',redZoneNearby:'⚡ लाल झोन जवळ',
  fetchingLocation:'स्थान मिळवत आहे...',locationUpdated:'स्थान अपडेट झाले',locationDenied:'स्थान प्रवेश नाकारला',unableGetLocation:'स्थान मिळवण्यात अक्षम',checkinFailed:'चेक-इन अयशस्वी.',dailyCheckinRecorded:'दैनिक चेक-इन नोंदवले ✓',checkedInAt:'चेक इन केले',verificationFailed:'सत्यापन अयशस्वी',youAreIn:'✓ तुम्ही आहात',zone:'झोन',notInAnyZone:'ℹ कोणत्याही झोनमध्ये नाही',noSafeZones:'सुरक्षित झोन नाही',nearestSafeZone:'जवळचा सुरक्षित झोन',sosTransmissionFailed:'SOS अयशस्वी!',anomalyReported:'विसंगती अहवाल दिला',tripUpdated:'प्रवास अपडेट झाला',
  reportSafetyAnomaly:'सुरक्षा विसंगती अहवाल',incidentType:'घटना प्रकार',suspiciousActivity:'संशयास्पद क्रियाकलाप',crimeTheft:'गुन्हा (चोरी/छळ)',medicalEmergency:'वैद्यकीय आणीबाणी',naturalDisaster:'नैसर्गिक आपत्ती',infrastructureHazard:'पायाभूत धोका',accidentOther:'अपघात / इतर',title:'शीर्षक',briefSummary:'संक्षिप्त सारांश',description:'वर्णन',detailsPlaceholder:'तपशील...',severity:'तीव्रता',autoDetected:'स्वयं-शोधले',submitReport:'अहवाल सबमिट करा',
  updateTravelPlan:'प्रवास योजना अपडेट',destinationRegion:'गंतव्य क्षेत्र',destinationPlaceholder:'उदा. तवांग जिल्हा',startDate:'सुरुवातीची तारीख',endDate:'शेवटची तारीख',saveChanges:'बदल जतन करा',
  iotDeviceSync:'IoT डिव्हाइस सिंक',bluetoothPair:'ब्लूटूथ पेअर',searchBluetooth:'जवळचे IoT बँड शोधा',searchingBluetooth:'ब्लूटूथ शोधत आहे...',wifiDirect:'वायफाय डायरेक्ट',connectViaNetwork:'स्थानिक नेटवर्कद्वारे कनेक्ट करा',wifiScanInitiated:'वायफाय स्कॅन सुरू',
  noWardAssigned:'तुमच्या खात्यात कोणताही वॉर्ड नाही.',yourArea:'तुमचे क्षेत्र',liveMonitoring:'लाइव्ह निरीक्षण',generalMonitoring:'सामान्य निरीक्षण · सर्व क्षेत्रे',healthy:'निरोगी',activeCircle:'सक्रिय वर्तुळ',holdForEmergency:'आणीबाणीसाठी दाबा',holdFor3Seconds:'मदत पाठवण्यासाठी 3 सेकंद दाबा',releaseToCancel:'SOS रद्द करण्यासाठी सोडा',helpDispatched:'मदत पाठवली',authoritiesNotified:'अधिकाऱ्यांना सूचित केले.',recentIncidents:'अलीकडील घटना',viewMap:'नकाशा पहा',noDescription:'वर्णन नाही.',wardClear:'वॉर्ड स्वच्छ आहे.',communityVitals:'समुदाय स्थिती',policePatrol:'पोलीस गस्त',communityVerified:'समुदाय सत्यापित',streetLight:'स्ट्रीट लाइट कव्हरेज',statusOperational:'स्थिती: चालू',checkinDue:'चेक-इन बाकी',loadingWardData:'वॉर्ड डेटा लोड होत आहे...',
  zoneSafetyStatus:'झोन सुरक्षा स्थिती',businessZone:'व्यापार झोन',dynamicScore:'गतिमान गुण',footfallOverview:'फूटफॉल अवलोकन',realTimeTraffic:'रिअल-टाइम ट्रॅफिक',activeVisitors:'सक्रिय अभ्यागत',nearbyTourists:'जवळचे पर्यटक',radius200m:'200 मी. त्रिज्या',verifiedTouristsInVicinity:'सत्यापित पर्यटक जवळपास',safetyAdvisories:'सुरक्षा सल्ला',postAdvisory:'सल्ला पोस्ट करा',noAdvisoryDetails:'सल्ला तपशील नाहीत.',noActiveAdvisories:'सक्रिय सल्ला नाही.',blockchainIdentityProof:'ब्लॉकचेन ओळख प्रमाण',validateCredentials:'Trackmate लेजरविरुद्ध प्रमाणपत्रे सत्यापित करा.',verify:'सत्यापित करा',ledgerVerified:'लेजर सत्यापित',authValid:'प्रमाणीकरण वैध',securityClearance:'सुरक्षा मंजूरी सत्यापित',verification:'सत्यापन',identityProofed:'ओळख प्रमाणित',pending:'प्रलंबित',role:'भूमिका',identityNotFound:'लेजरमध्ये ओळख नाही.',verificationUnavailable:'सत्यापन सेवा अनुपलब्ध.',
  holdForBusinessSOS:'व्यापार आणीबाणी SOS दाबा',holdFor3SecondsTrigger:'रेड अलार्म 3 सेकंद दाबा',releaseToCancel2:'SOS रद्द करा',sosDispatched:'SOS अधिकाऱ्यांना पाठवला',authorityReceived:'प्राधिकरण पॅनेलने हा ट्रिगर रिअल टाइममध्ये प्राप्त केला.',loadingBusinessData:'व्यापार डेटा लोड होत आहे...',
  commandDashboard:'कमांड डॅशबोर्ड',authorityOfficer:'प्राधिकरण अधिकारी',liveUsers:'लाइव्ह वापरकर्ते',openIncidents:'खुल्या घटना',sosLastHour:'SOS (मागील तास)',totalProfiles:'एकूण प्रोफाइल',needsAttention:'लक्ष आवश्यक',liveTrackingActive:'लाइव्ह ट्रॅकिंग सक्रिय',authorityCommandMap:'प्राधिकरण कमांड लाइव्ह मॅप',trackingDevices:'ट्रॅकिंग',liveDevicesAcrossZones:'लाइव्ह डिव्हाइसेस झोनमध्ये.',resetView:'व्ह्यू रीसेट',focusLive:'लाइव्ह फोकस',drawZone:'झोन काढा',mapLegend:'मॅप लीजेंड',safeZone:'सुरक्षित झोन',moderateZone:'मध्यम झोन',highRisk:'उच्च जोखीम',restrictedZone:'प्रतिबंधित झोन',tourist:'पर्यटक',resident:'रहिवासी',clearUserFilter:'फिल्टर काढा ✕',
  checkinToday:'आज',touristCheckins24h:'मागील 24 तासांतील पर्यटक चेक-इन',noCheckins24h:'24 तासांत चेक-इन नाहीत.',locationCheckin:'स्थान चेक-इन',checkedInStatus:'चेक इन केले',liveAlertFeed:'लाइव्ह सतर्कता फीड',clickRowToIsolate:'नकाशावर अहवालकर्ता वेगळा करण्यासाठी क्लिक करा',connectingToFeed:'नोड फीडला कनेक्ट होत आहे...',severityCol:'तीव्रता',titleZone:'शीर्षक / झोन',reporter:'अहवालकर्ता',status:'स्थिती',actions:'कृती',unknownLocation:'अज्ञात स्थान',system:'सिस्टम',acknowledge:'मान्य करा',resolve:'निराकरण करा',done:'✓ पूर्ण',noActiveIncidents:'सक्रिय घटना नाहीत.',redAlert:'रेड अलर्ट',personInDanger:'धोक्यातील व्यक्ती',unknownUser:'अज्ञात वापरकर्ता',realDanger:'खरा धोका',falseAlarm:'खोटा अलार्म',confidence:'विश्वास',trackLocation:'स्थान ट्रॅक करा',zoneAdded:'झोन जोडला.',zoneDeleted:'झोन हटवला.',failedUpdateIncident:'घटना अपडेट अयशस्वी.',failedSaveZone:'झोन जतन अयशस्वी',failedDeleteZone:'झोन हटवणे अयशस्वी.',deleteZoneConfirm:'हा झोन हटवायचा?',reporterLocationUnavailable:'अहवालकर्त्याचे स्थान अनुपलब्ध.',searchZonesPlaceholder:'झोन शोधा...',
};
export default mr;
