import type { TranslationKeys } from './en';
const pa: Partial<TranslationKeys> = {
  appName:'TRACKMATE',logout:'ਲੌਗ ਆਊਟ',score:'ਸਕੋਰ',online:'ਔਨਲਾਈਨ',refresh:'ਰਿਫ੍ਰੈਸ਼',save:'ਸੰਭਾਲੋ',cancel:'ਰੱਦ ਕਰੋ',submit:'ਜਮ੍ਹਾ ਕਰੋ',close:'ਬੰਦ ਕਰੋ',loading:'ਲੋਡ ਹੋ ਰਿਹਾ...',safe:'ਸੁਰੱਖਿਅਤ',moderate:'ਮੱਧਮ',restricted:'ਪ੍ਰਤਿਬੰਧਿਤ',high:'ਉੱਚ',low:'ਘੱਟ',medium:'ਮੱਧਮ',critical:'ਗੰਭੀਰ',active:'ਸਰਗਰਮ',resolved:'ਹੱਲ ਹੋਇਆ',acknowledged:'ਸਵੀਕਾਰ ਕੀਤਾ',unknown:'ਅਣਜਾਣ',language:'ਭਾਸ਼ਾ',selectLanguage:'ਭਾਸ਼ਾ ਚੁਣੋ',
  safetyScore:'ਸੁਰੱਖਿਆ ਸਕੋਰ',authorityNode:'ਅਥਾਰਟੀ ਨੋਡ',navigation:'ਨੈਵੀਗੇਸ਼ਨ',dashboard:'ਡੈਸ਼ਬੋਰਡ',incidents:'ਘਟਨਾਵਾਂ',userManagement:'ਉਪਭੋਗਤਾ ਪ੍ਰਬੰਧਨ',tourists:'ਸੈਲਾਨੀ',residents:'ਨਿਵਾਸੀ',businesses:'ਕਾਰੋਬਾਰ',tools:'ਸੰਦ',dailyCheckins:'ਰੋਜ਼ਾਨਾ ਚੈੱਕ-ਇਨ',zoneManagement:'ਜ਼ੋਨ ਪ੍ਰਬੰਧਨ',efirSystem:'ਈ-ਐਫਆਈਆਰ ਸਿਸਟਮ',safetyAnalytics:'ਸੁਰੱਖਿਆ ਵਿਸ਼ਲੇਸ਼ਣ',sendAlert:'ਚੇਤਾਵਨੀ ਭੇਜੋ',officer:'ਅਧਿਕਾਰੀ',
  map:'ਨਕਸ਼ਾ',trip:'ਯਾਤਰਾ',profile:'ਪ੍ਰੋਫਾਈਲ',local:'ਸਥਾਨਕ',feed:'ਫੀਡ',report:'ਰਿਪੋਰਟ',intel:'ਜਾਣਕਾਰੀ',business:'ਕਾਰੋਬਾਰ',
  login:'ਲੌਗਇਨ',getStarted:'ਸ਼ੁਰੂ ਕਰੋ',unifiedSafetyPlatform:'ਏਕੀਕ੍ਰਿਤ ਸੁਰੱਖਿਆ ਪਲੇਟਫਾਰਮ v3',heroTitle:'ਰੀਅਲ-ਟਾਈਮ ਸ਼ਹਿਰ ਸੁਰੱਖਿਆ ਜਾਣਕਾਰੀ',heroTitleHighlight:' ਨਿਵਾਸੀਆਂ, ਸੈਲਾਨੀਆਂ ਅਤੇ ਪ੍ਰਤੀਕਿਰਿਆ ਟੀਮਾਂ ਲਈ',heroDescription:'TrackMate ਲਾਈਵ ਨਕਸ਼ੇ, AI ਅਸਧਾਰਨਤਾ ਖੋਜ ਅਤੇ ਐਮਰਜੈਂਸੀ ਵਰਕਫਲੋ ਨੂੰ ਜੋੜਦਾ ਹੈ.',enterPlatform:'ਪਲੇਟਫਾਰਮ ਵਿੱਚ ਦਾਖਲ ਹੋਵੋ',alreadyHaveAccess:'ਪਹਿਲਾਂ ਹੀ ਐਕਸੈਸ ਹੈ',selectAccessRole:'ਆਪਣੀ ਭੂਮਿਕਾ ਚੁਣੋ',onePlatform:'ਇੱਕ ਪਲੇਟਫਾਰਮ, ਭੂਮਿਕਾ-ਵਿਸ਼ੇਸ਼ ਵਰਕਫਲੋ',roleDescription:'ਸਹੀ ਸੰਦ ਅਨਲੌਕ ਕਰਨ ਲਈ ਆਪਣੀਆਂ ਜ਼ਿੰਮੇਵਾਰੀਆਂ ਨਾਲ ਮੇਲ ਖਾਂਦੀ ਭੂਮਿਕਾ ਵਰਤੋ.',continueAs:'ਵਜੋਂ ਜਾਰੀ ਰੱਖੋ',coreCapabilities:'ਮੁੱਖ ਸਮਰੱਥਾਵਾਂ',coreCapabilitiesDesc:'ਜਨਤਕ ਉਪਭੋਗਤਾਵਾਂ ਅਤੇ ਕਮਾਂਡ ਟੀਮਾਂ ਵਿਚਕਾਰ ਤੇਜ਼ ਤਾਲਮੇਲ.',footerBrand:'TrackMate ਨਾਗਰਿਕ ਸੁਰੱਖਿਆ ਪਲੇਟਫਾਰਮ',footerCopyright:'© 2026 TrackMate. ਜੁੜੇ ਸ਼ਹਿਰਾਂ ਲਈ ਤਾਲਮੇਲ ਸੁਰੱਖਿਆ.',
  touristLabel:'ਸੈਲਾਨੀ',residentLabel:'ਨਿਵਾਸੀ',businessLabel:'ਕਾਰੋਬਾਰ',authorityLabel:'ਅਥਾਰਟੀ',touristDesc:'ਰੀਅਲ-ਟਾਈਮ ਚੇਤਾਵਨੀਆਂ ਅਤੇ SOS ਸਹਾਇਤਾ ਨਾਲ ਭਰੋਸੇ ਨਾਲ ਯਾਤਰਾ ਕਰੋ.',residentDesc:'ਤੁਰੰਤ ਘਟਨਾ ਰਿਪੋਰਟਿੰਗ ਨਾਲ ਆਪਣੇ ਮੁਹੱਲੇ ਦੀ ਰੱਖਿਆ ਕਰੋ.',businessDesc:'AI ਵਰਤ ਕੇ ਆਪਣੀ ਜਾਇਦਾਦ ਦੇ ਆਲੇ-ਦੁਆਲੇ ਖ਼ਤਰੇ ਦੀ ਨਿਗਰਾਨੀ ਕਰੋ.',authorityDesc:'ਕਮਾਂਡ ਵਿਸ਼ਲੇਸ਼ਣ ਅਤੇ ਈ-ਐਫਆਈਆਰ ਨਾਲ ਸ਼ਹਿਰ ਸੁਰੱਖਿਆ ਓਪਰੇਸ਼ਨ ਤਾਲਮੇਲ ਕਰੋ.',
  liveMonitoringGrid:'ਲਾਈਵ ਮਾਨੀਟਰਿੰਗ ਗ੍ਰਿੱਡ',liveMonitoringGridDesc:'ਚਲ-ਫਿਰ ਅਤੇ ਜ਼ੋਨ ਖ਼ਤਰੇ ਨੂੰ ਟ੍ਰੈਕ ਕਰੋ.',anomalyDetection:'ਅਸਧਾਰਨਤਾ ਖੋਜ',anomalyDetectionDesc:'AI ਮਾਡਲ ਅਸਾਧਾਰਨ ਪੈਟਰਨ ਪਛਾਣਦੇ ਹਨ.',trustedIdentity:'ਭਰੋਸੇਯੋਗ ਪਛਾਣ',trustedIdentityDesc:'ਸੁਰੱਖਿਅਤ ਤਸਦੀਕ ਵਰਕਫਲੋ ਸਹੀ ਜਵਾਬ ਦੇਣ ਵਾਲਿਆਂ ਨੂੰ ਯਕੀਨੀ ਬਣਾਉਂਦੇ ਹਨ.',
  systemProtected:'ਸਿਸਟਮ ਸੁਰੱਖਿਅਤ — ਨਿਗਰਾਨੀ ਸਰਗਰਮ',locationMonitored:'ਤੁਹਾਡੀ ਟਿਕਾਣਾ ਨਿਗਰਾਨੀ ਵਿੱਚ ਹੈ',localAuthorities:'ਸਥਾਨਕ ਅਧਿਕਾਰੀ',liveSafetyGIS:'ਲਾਈਵ ਸੁਰੱਖਿਆ GIS',locateMe:'ਮੈਨੂੰ ਲੱਭੋ',searchZones:'ਜ਼ੋਨ ਲੱਭੋ...',activeItinerary:'ਸਰਗਰਮ ਯਾਤਰਾ ਪ੍ਰੋਗਰਾਮ',destination:'ਮੰਜ਼ਿਲ',duration:'ਮਿਆਦ',updatePlan:'ਯੋਜਨਾ ਅੱਪਡੇਟ',verifyStay:'ਠਹਿਰ ਤਸਦੀਕ',noActiveTrip:'ਕੋਈ ਸਰਗਰਮ ਯਾਤਰਾ ਨਹੀਂ.',startPlanning:'ਯੋਜਨਾਬੰਦੀ ਸ਼ੁਰੂ ਕਰੋ',safetyServices:'ਸੁਰੱਖਿਆ ਸੇਵਾਵਾਂ',dailyCheckin:'ਰੋਜ਼ਾਨਾ ਚੈੱਕ-ਇਨ',checkedIn:'ਚੈੱਕ ਇਨ ਹੋਇਆ ✓',reportAnomaly:'ਅਸਧਾਰਨਤਾ ਰਿਪੋਰਟ',iotSync:'IoT ਸਿੰਕ',safeHouse:'ਸੇਫ ਹਾਊਸ',safetyBroadcasts:'ਸੁਰੱਖਿਆ ਪ੍ਰਸਾਰਣ',allSectorsClear:'ਸਾਰੇ ਸੈਕਟਰ ਸਾਫ਼. ਯਾਤਰਾ ਦਾ ਅਨੰਦ ਮਾਣੋ!',holdSOS:'3 ਸਕਿੰਟ ਦਬਾਓ',alertSent:'ਚੇਤਾਵਨੀ ਭੇਜੀ ਗਈ',holding:'ਦਬਾਇਆ ਹੋਇਆ',redZoneNearby:'⚡ ਲਾਲ ਜ਼ੋਨ ਨੇੜੇ',
  fetchingLocation:'ਟਿਕਾਣਾ ਲੱਭ ਰਿਹਾ...',locationUpdated:'ਟਿਕਾਣਾ ਅੱਪਡੇਟ ਹੋਇਆ',locationDenied:'ਟਿਕਾਣਾ ਐਕਸੈਸ ਇਨਕਾਰ',unableGetLocation:'ਟਿਕਾਣਾ ਲੱਭਣ ਤੋਂ ਅਸਮਰੱਥ',checkinFailed:'ਚੈੱਕ-ਇਨ ਅਸਫ਼ਲ.',dailyCheckinRecorded:'ਚੈੱਕ-ਇਨ ਦਰਜ ✓',checkedInAt:'ਚੈੱਕ ਇਨ ਹੋਇਆ',verificationFailed:'ਤਸਦੀਕ ਅਸਫ਼ਲ',youAreIn:'✓ ਤੁਸੀਂ ਹੋ',zone:'ਜ਼ੋਨ',notInAnyZone:'ℹ ਕਿਸੇ ਰਜਿਸਟਰਡ ਜ਼ੋਨ ਵਿੱਚ ਨਹੀਂ',noSafeZones:'ਸੁਰੱਖਿਅਤ ਜ਼ੋਨ ਨਹੀਂ',nearestSafeZone:'ਨੇੜਲਾ ਸੁਰੱਖਿਅਤ ਜ਼ੋਨ',sosTransmissionFailed:'SOS ਅਸਫ਼ਲ!',anomalyReported:'ਅਸਧਾਰਨਤਾ ਰਿਪੋਰਟ ਹੋਈ',tripUpdated:'ਯਾਤਰਾ ਅੱਪਡੇਟ ਹੋਈ',
  reportSafetyAnomaly:'ਸੁਰੱਖਿਆ ਅਸਧਾਰਨਤਾ ਰਿਪੋਰਟ',incidentType:'ਘਟਨਾ ਕਿਸਮ',suspiciousActivity:'ਸ਼ੱਕੀ ਗਤੀਵਿਧੀ',crimeTheft:'ਅਪਰਾਧ (ਚੋਰੀ/ਪ੍ਰੇਸ਼ਾਨੀ)',medicalEmergency:'ਡਾਕਟਰੀ ਐਮਰਜੈਂਸੀ',naturalDisaster:'ਕੁਦਰਤੀ ਆਫ਼ਤ',infrastructureHazard:'ਢਾਂਚਾ ਖ਼ਤਰਾ',accidentOther:'ਦੁਰਘਟਨਾ / ਹੋਰ',title:'ਸਿਰਲੇਖ',briefSummary:'ਸੰਖੇਪ ਸਾਰ',description:'ਵੇਰਵਾ',detailsPlaceholder:'ਵੇਰਵੇ...',severity:'ਗੰਭੀਰਤਾ',autoDetected:'ਆਟੋ-ਖੋਜ',submitReport:'ਰਿਪੋਰਟ ਜਮ੍ਹਾ ਕਰੋ',
  updateTravelPlan:'ਯਾਤਰਾ ਯੋਜਨਾ ਅੱਪਡੇਟ',destinationRegion:'ਮੰਜ਼ਿਲ ਖੇਤਰ',destinationPlaceholder:'ਜਿਵੇਂ ਤਵਾਂਗ ਜ਼ਿਲ੍ਹਾ',startDate:'ਸ਼ੁਰੂ ਤਾਰੀਖ',endDate:'ਅੰਤ ਤਾਰੀਖ',saveChanges:'ਬਦਲਾਅ ਸੰਭਾਲੋ',
  iotDeviceSync:'IoT ਡਿਵਾਈਸ ਸਿੰਕ',bluetoothPair:'ਬਲੂਟੁੱਥ ਪੇਅਰ',searchBluetooth:'ਨੇੜਲੇ IoT ਬੈਂਡ ਲੱਭੋ',searchingBluetooth:'ਬਲੂਟੁੱਥ ਲੱਭ ਰਿਹਾ...',wifiDirect:'ਵਾਈ-ਫਾਈ ਡਾਇਰੈਕਟ',connectViaNetwork:'ਸਥਾਨਕ ਨੈੱਟਵਰਕ ਰਾਹੀਂ ਜੋੜੋ',wifiScanInitiated:'ਵਾਈ-ਫਾਈ ਸਕੈਨ ਸ਼ੁਰੂ',
  noWardAssigned:'ਤੁਹਾਡੇ ਖਾਤੇ ਵਿੱਚ ਕੋਈ ਵਾਰਡ ਨਹੀਂ.',yourArea:'ਤੁਹਾਡਾ ਖੇਤਰ',liveMonitoring:'ਲਾਈਵ ਨਿਗਰਾਨੀ',generalMonitoring:'ਆਮ ਨਿਗਰਾਨੀ · ਸਾਰੇ ਖੇਤਰ',healthy:'ਸਿਹਤਮੰਦ',activeCircle:'ਸਰਗਰਮ ਸਰਕਲ',holdForEmergency:'ਐਮਰਜੈਂਸੀ ਲਈ ਦਬਾਓ',holdFor3Seconds:'ਮਦਦ ਭੇਜਣ ਲਈ 3 ਸਕਿੰਟ ਦਬਾਓ',releaseToCancel:'SOS ਰੱਦ ਕਰਨ ਲਈ ਛੱਡੋ',helpDispatched:'ਮਦਦ ਭੇਜੀ ਗਈ',authoritiesNotified:'ਅਧਿਕਾਰੀਆਂ ਨੂੰ ਸੂਚਿਤ ਕੀਤਾ.',recentIncidents:'ਹਾਲੀਆ ਘਟਨਾਵਾਂ',viewMap:'ਨਕਸ਼ਾ ਦੇਖੋ',noDescription:'ਵੇਰਵਾ ਨਹੀਂ.',wardClear:'ਵਾਰਡ ਸਾਫ਼ ਹੈ.',communityVitals:'ਭਾਈਚਾਰਕ ਸਥਿਤੀ',policePatrol:'ਪੁਲਿਸ ਗਸ਼ਤ',communityVerified:'ਭਾਈਚਾਰਾ ਤਸਦੀਕ',streetLight:'ਸਟ੍ਰੀਟ ਲਾਈਟ ਕਵਰੇਜ',statusOperational:'ਸਥਿਤੀ: ਚਾਲੂ',checkinDue:'ਚੈੱਕ-ਇਨ ਬਕਾਇਆ',loadingWardData:'ਵਾਰਡ ਡੇਟਾ ਲੋਡ...',
  zoneSafetyStatus:'ਜ਼ੋਨ ਸੁਰੱਖਿਆ ਸਥਿਤੀ',businessZone:'ਵਪਾਰ ਜ਼ੋਨ',dynamicScore:'ਗਤੀਸ਼ੀਲ ਸਕੋਰ',footfallOverview:'ਫੁੱਟਫਾਲ ਸੰਖੇਪ',realTimeTraffic:'ਰੀਅਲ-ਟਾਈਮ ਟ੍ਰੈਫਿਕ',activeVisitors:'ਸਰਗਰਮ ਸੈਲਾਨੀ',nearbyTourists:'ਨੇੜਲੇ ਸੈਲਾਨੀ',radius200m:'200 ਮੀ ਘੇਰਾ',verifiedTouristsInVicinity:'ਤਸਦੀਕ ਸੈਲਾਨੀ ਨੇੜੇ',safetyAdvisories:'ਸੁਰੱਖਿਆ ਸਲਾਹ',postAdvisory:'ਸਲਾਹ ਪੋਸਟ',noAdvisoryDetails:'ਸਲਾਹ ਵੇਰਵੇ ਨਹੀਂ.',noActiveAdvisories:'ਸਰਗਰਮ ਸਲਾਹ ਨਹੀਂ.',blockchainIdentityProof:'ਬਲਾਕਚੇਨ ਪਛਾਣ ਸਬੂਤ',validateCredentials:'Trackmate ਲੈਜ਼ਰ ਨਾਲ ਤਸਦੀਕ ਕਰੋ.',verify:'ਤਸਦੀਕ',ledgerVerified:'ਲੈਜ਼ਰ ਤਸਦੀਕ',authValid:'ਪ੍ਰਮਾਣੀਕਰਨ ਵੈਧ',securityClearance:'ਸੁਰੱਖਿਆ ਮਨਜ਼ੂਰੀ ਤਸਦੀਕ',verification:'ਤਸਦੀਕ',identityProofed:'ਪਛਾਣ ਸਾਬਤ',pending:'ਬਕਾਇਆ',role:'ਭੂਮਿਕਾ',identityNotFound:'ਲੈਜ਼ਰ ਵਿੱਚ ਪਛਾਣ ਨਹੀਂ.',verificationUnavailable:'ਤਸਦੀਕ ਸੇਵਾ ਉਪਲਬਧ ਨਹੀਂ.',
  holdForBusinessSOS:'ਵਪਾਰ SOS ਦਬਾਓ',holdFor3SecondsTrigger:'ਰੈੱਡ ਅਲਾਰਮ 3 ਸਕਿੰਟ ਦਬਾਓ',releaseToCancel2:'SOS ਰੱਦ',sosDispatched:'SOS ਅਧਿਕਾਰੀਆਂ ਨੂੰ ਭੇਜਿਆ',authorityReceived:'ਅਥਾਰਟੀ ਪੈਨਲ ਨੇ ਰੀਅਲ ਟਾਈਮ ਵਿੱਚ ਪ੍ਰਾਪਤ ਕੀਤਾ.',loadingBusinessData:'ਵਪਾਰ ਡੇਟਾ ਲੋਡ...',
  commandDashboard:'ਕਮਾਂਡ ਡੈਸ਼ਬੋਰਡ',authorityOfficer:'ਅਥਾਰਟੀ ਅਧਿਕਾਰੀ',liveUsers:'ਲਾਈਵ ਉਪਭੋਗਤਾ',openIncidents:'ਖੁੱਲ੍ਹੀਆਂ ਘਟਨਾਵਾਂ',sosLastHour:'SOS (ਆਖ਼ਰੀ ਘੰਟਾ)',totalProfiles:'ਕੁੱਲ ਪ੍ਰੋਫਾਈਲ',needsAttention:'ਧਿਆਨ ਲੋੜੀਂਦਾ',liveTrackingActive:'ਲਾਈਵ ਟ੍ਰੈਕਿੰਗ ਸਰਗਰਮ',authorityCommandMap:'ਅਥਾਰਟੀ ਕਮਾਂਡ ਲਾਈਵ ਨਕਸ਼ਾ',trackingDevices:'ਟ੍ਰੈਕਿੰਗ',liveDevicesAcrossZones:'ਲਾਈਵ ਡਿਵਾਈਸ ਜ਼ੋਨਾਂ ਵਿੱਚ.',resetView:'ਵਿਊ ਰੀਸੈੱਟ',focusLive:'ਲਾਈਵ ਫੋਕਸ',drawZone:'ਜ਼ੋਨ ਬਣਾਓ',mapLegend:'ਨਕਸ਼ਾ ਲੀਜੈਂਡ',safeZone:'ਸੁਰੱਖਿਅਤ ਜ਼ੋਨ',moderateZone:'ਮੱਧਮ ਜ਼ੋਨ',highRisk:'ਉੱਚ ਖ਼ਤਰਾ',restrictedZone:'ਪ੍ਰਤਿਬੰਧਿਤ ਜ਼ੋਨ',tourist:'ਸੈਲਾਨੀ',resident:'ਨਿਵਾਸੀ',clearUserFilter:'ਫਿਲਟਰ ਹਟਾਓ ✕',
  checkinToday:'ਅੱਜ',touristCheckins24h:'ਪਿਛਲੇ 24 ਘੰਟੇ ਚੈੱਕ-ਇਨ',noCheckins24h:'24 ਘੰਟਿਆਂ ਵਿੱਚ ਚੈੱਕ-ਇਨ ਨਹੀਂ.',locationCheckin:'ਟਿਕਾਣਾ ਚੈੱਕ-ਇਨ',checkedInStatus:'ਚੈੱਕ ਇਨ ਹੋਇਆ',liveAlertFeed:'ਲਾਈਵ ਚੇਤਾਵਨੀ ਫੀਡ',clickRowToIsolate:'ਨਕਸ਼ੇ ਤੇ ਰਿਪੋਰਟਰ ਨੂੰ ਅਲੱਗ ਕਰਨ ਲਈ ਕਲਿੱਕ ਕਰੋ',connectingToFeed:'ਫੀਡ ਨਾਲ ਜੁੜ ਰਿਹਾ...',severityCol:'ਗੰਭੀਰਤਾ',titleZone:'ਸਿਰਲੇਖ / ਜ਼ੋਨ',reporter:'ਰਿਪੋਰਟਰ',status:'ਸਥਿਤੀ',actions:'ਕਾਰਵਾਈਆਂ',unknownLocation:'ਅਣਜਾਣ ਟਿਕਾਣਾ',system:'ਸਿਸਟਮ',acknowledge:'ਸਵੀਕਾਰ ਕਰੋ',resolve:'ਹੱਲ ਕਰੋ',done:'✓ ਹੋਇਆ',noActiveIncidents:'ਸਰਗਰਮ ਘਟਨਾਵਾਂ ਨਹੀਂ.',redAlert:'ਰੈੱਡ ਅਲਰਟ',personInDanger:'ਖ਼ਤਰੇ ਵਿੱਚ ਵਿਅਕਤੀ',unknownUser:'ਅਣਜਾਣ ਉਪਭੋਗਤਾ',realDanger:'ਅਸਲ ਖ਼ਤਰਾ',falseAlarm:'ਝੂਠਾ ਅਲਾਰਮ',confidence:'ਭਰੋਸਾ',trackLocation:'ਟਿਕਾਣਾ ਟ੍ਰੈਕ',zoneAdded:'ਜ਼ੋਨ ਜੋੜਿਆ.',zoneDeleted:'ਜ਼ੋਨ ਹਟਾਇਆ.',failedUpdateIncident:'ਘਟਨਾ ਅੱਪਡੇਟ ਅਸਫ਼ਲ.',failedSaveZone:'ਜ਼ੋਨ ਸੰਭਾਲਣਾ ਅਸਫ਼ਲ',failedDeleteZone:'ਜ਼ੋਨ ਹਟਾਉਣਾ ਅਸਫ਼ਲ.',deleteZoneConfirm:'ਇਹ ਜ਼ੋਨ ਹਟਾਉਣਾ?',reporterLocationUnavailable:'ਰਿਪੋਰਟਰ ਟਿਕਾਣਾ ਉਪਲਬਧ ਨਹੀਂ.',searchZonesPlaceholder:'ਜ਼ੋਨ ਲੱਭੋ...',
};
export default pa;
