import type { TranslationKeys } from './en';
const ta: TranslationKeys = {
  appName:'TRACKMATE',logout:'வெளியேறு',score:'மதிப்பெண்',online:'ஆன்லைன்',refresh:'புதுப்பி',save:'சேமி',cancel:'ரத்து',submit:'சமர்ப்பி',close:'மூடு',loading:'ஏற்றுகிறது...',safe:'பாதுகாப்பான',moderate:'மிதமான',restricted:'தடைசெய்யப்பட்ட',high:'அதிக',low:'குறைவு',medium:'நடுத்தர',critical:'தீவிர',active:'செயலில்',resolved:'தீர்க்கப்பட்டது',acknowledged:'ஏற்றுக்கொள்ளப்பட்டது',unknown:'அறியப்படாத',language:'மொழி',selectLanguage:'மொழி தேர்ந்தெடுக்கவும்',
  safetyScore:'பாதுகாப்பு மதிப்பெண்',authorityNode:'அதிகார நோட்',navigation:'வழிசெலுத்தல்',dashboard:'டாஷ்போர்டு',incidents:'சம்பவங்கள்',userManagement:'பயனர் மேலாண்மை',tourists:'சுற்றுலா பயணிகள்',residents:'குடியிருப்பாளர்கள்',businesses:'வணிகங்கள்',tools:'கருவிகள்',dailyCheckins:'தினசரி செக்-இன்',zoneManagement:'மண்டல மேலாண்மை',efirSystem:'இ-எஃப்ஐஆர் அமைப்பு',safetyAnalytics:'பாதுகாப்பு பகுப்பாய்வு',sendAlert:'எச்சரிக்கை அனுப்பு',officer:'அதிகாரி',
  map:'வரைபடம்',trip:'பயணம்',profile:'சுயவிவரம்',local:'உள்ளூர்',feed:'ஊட்டம்',report:'அறிக்கை',intel:'தகவல்',business:'வணிகம்',
  login:'உள்நுழைவு',getStarted:'தொடங்கு',unifiedSafetyPlatform:'ஒருங்கிணைந்த பாதுகாப்பு தளம் v3',heroTitle:'நிகழ்நேர நகர பாதுகாப்பு நுண்ணறிவு',heroTitleHighlight:' குடியிருப்பாளர்கள், பார்வையாளர்கள் மற்றும் மறுமொழி குழுக்களுக்கு',heroDescription:'TrackMate நேரடி வரைபடங்கள், AI முரண் கண்டறிதல் மற்றும் அவசர பணிப்பாய்வுகளை இணைக்கிறது.',enterPlatform:'தளத்தில் நுழையுங்கள்',alreadyHaveAccess:'ஏற்கனவே அணுகல் உள்ளது',selectAccessRole:'உங்கள் பங்கைத் தேர்ந்தெடுக்கவும்',onePlatform:'ஒரு தளம், பங்கு-குறிப்பிட்ட பணிப்பாய்வுகள்',roleDescription:'சரியான கருவிகளைத் திறக்க உங்கள் பொறுப்புகளுக்கு பொருந்தும் பங்கைப் பயன்படுத்துங்கள்.',continueAs:'ஆக தொடரவும்',coreCapabilities:'முக்கிய திறன்கள்',coreCapabilitiesDesc:'பொது பயனர்கள் மற்றும் கட்டளை குழுக்களுக்கிடையில் விரைவான ஒருங்கிணைப்பு.',footerBrand:'TrackMate குடிமக்கள் பாதுகாப்பு தளம்',footerCopyright:'© 2026 TrackMate. இணைக்கப்பட்ட நகரங்களுக்கான ஒருங்கிணைந்த பாதுகாப்பு.',
  touristLabel:'சுற்றுலா பயணி',residentLabel:'குடியிருப்பாளர்',businessLabel:'வணிகம்',authorityLabel:'அதிகாரம்',touristDesc:'நிகழ்நேர எச்சரிக்கைகள் மற்றும் SOS ஆதரவுடன் நம்பிக்கையுடன் பயணிக்கவும்.',residentDesc:'உடனடி சம்பவ அறிக்கையிடல் மூலம் உங்கள் சுற்றுப்புறத்தைப் பாதுகாக்கவும்.',businessDesc:'AI பயன்படுத்தி உங்கள் சொத்து சுற்றி ஆபத்தை கண்காணிக்கவும்.',authorityDesc:'கட்டளை பகுப்பாய்வு மற்றும் இ-எஃப்ஐஆர் மூலம் நகர பாதுகாப்பு செயல்பாடுகளை ஒருங்கிணைக்கவும்.',
  liveMonitoringGrid:'நேரடி கண்காணிப்பு கட்டம்',liveMonitoringGridDesc:'இயக்கம் மற்றும் மண்டல ஆபத்தைக் கண்காணிக்கவும்.',anomalyDetection:'முரண் கண்டறிதல்',anomalyDetectionDesc:'AI மாதிரிகள் அசாதாரண வடிவங்களை அடையாளம் காணும்.',trustedIdentity:'நம்பகமான அடையாளம்',trustedIdentityDesc:'பாதுகாப்பான சரிபார்ப்பு பணிப்பாய்வுகள் சரியான பதிலளிப்பாளர்களை உறுதிப்படுத்துகின்றன.',
  systemProtected:'அமைப்பு பாதுகாக்கப்பட்டுள்ளது — கண்காணிப்பு செயலில்',locationMonitored:'உங்கள் இருப்பிடம் கண்காணிக்கப்படுகிறது',localAuthorities:'உள்ளூர் அதிகாரிகள்',liveSafetyGIS:'நேரடி பாதுகாப்பு GIS',locateMe:'என்னைக் கண்டறி',searchZones:'மண்டலங்களைத் தேடு...',activeItinerary:'செயலில் உள்ள பயண திட்டம்',destination:'இலக்கு',duration:'கால அளவு',updatePlan:'திட்டத்தைப் புதுப்பி',verifyStay:'தங்குதலை சரிபார்',noActiveTrip:'செயலில் உள்ள பயணம் இல்லை.',startPlanning:'திட்டமிடலைத் தொடங்கு',safetyServices:'பாதுகாப்பு சேவைகள்',dailyCheckin:'தினசரி செக்-இன்',checkedIn:'செக் இன் ஆனது ✓',reportAnomaly:'முரணை அறிவி',iotSync:'IoT ஒத்திசை',safeHouse:'பாதுகாப்பு இல்லம்',safetyBroadcasts:'பாதுகாப்பு ஒளிபரப்புகள்',allSectorsClear:'எல்லா பிரிவுகளும் தெளிவாக. பயணத்தை அனுபவியுங்கள்!',holdSOS:'3 வினாடி அழுத்து',alertSent:'எச்சரிக்கை அனுப்பப்பட்டது',holding:'அழுத்துகிறது',redZoneNearby:'⚡ சிவப்பு மண்டலம் அருகில்',
  fetchingLocation:'இருப்பிடம் பெறுகிறது...',locationUpdated:'இருப்பிடம் புதுப்பிக்கப்பட்டது',locationDenied:'இருப்பிட அணுகல் மறுக்கப்பட்டது',unableGetLocation:'இருப்பிடம் பெற இயலவில்லை',checkinFailed:'செக்-இன் தோல்வி.',dailyCheckinRecorded:'செக்-இன் பதிவு ✓',checkedInAt:'செக் இன் ஆனது',verificationFailed:'சரிபார்ப்பு தோல்வி',youAreIn:'✓ நீங்கள் இருக்கிறீர்கள்',zone:'மண்டலம்',notInAnyZone:'ℹ எந்த பதிவு செய்யப்பட்ட மண்டலத்திலும் இல்லை',noSafeZones:'பாதுகாப்பான மண்டலங்கள் இல்லை',nearestSafeZone:'அருகிலுள்ள பாதுகாப்பான மண்டலம்',sosTransmissionFailed:'SOS தோல்வி!',anomalyReported:'முரண் அறிவிக்கப்பட்டது',tripUpdated:'பயணம் புதுப்பிக்கப்பட்டது',
  reportSafetyAnomaly:'பாதுகாப்பு முரண் அறிக்கை',incidentType:'சம்பவ வகை',suspiciousActivity:'சந்தேகத்திற்குரிய செயல்பாடு',crimeTheft:'குற்றம் (திருட்டு/தொல்லை)',medicalEmergency:'மருத்துவ அவசரம்',naturalDisaster:'இயற்கை பேரிடர்',infrastructureHazard:'உள்கட்டமைப்பு ஆபத்து',accidentOther:'விபத்து / மற்றவை',title:'தலைப்பு',briefSummary:'சுருக்கம்',description:'விவரம்',detailsPlaceholder:'விவரங்கள்...',severity:'தீவிரம்',autoDetected:'தானியங்கி-கண்டறிதல்',submitReport:'அறிக்கை சமர்ப்பி',
  updateTravelPlan:'பயண திட்ட புதுப்பிப்பு',destinationRegion:'இலக்கு பிரதேசம்',destinationPlaceholder:'எ.கா. தவாங் மாவட்டம்',startDate:'தொடக்க தேதி',endDate:'முடிவு தேதி',saveChanges:'மாற்றங்களை சேமி',
  iotDeviceSync:'IoT சாதன ஒத்திசை',bluetoothPair:'புளூடூத் இணை',searchBluetooth:'அருகிலுள்ள IoT பட்டைகளைத் தேடு',searchingBluetooth:'புளூடூத் தேடுகிறது...',wifiDirect:'வைஃபை டைரக்ட்',connectViaNetwork:'உள்ளூர் நெட்வொர்க் வழியாக இணை',wifiScanInitiated:'வைஃபை ஸ்கேன் தொடங்கியது',
  noWardAssigned:'உங்கள் கணக்கில் வார்டு இல்லை.',yourArea:'உங்கள் பகுதி',liveMonitoring:'நேரடி கண்காணிப்பு',generalMonitoring:'பொது கண்காணிப்பு · அனைத்து பகுதிகள்',healthy:'ஆரோக்கியம்',activeCircle:'செயலில் வட்டம்',holdForEmergency:'அவசரத்திற்கு அழுத்து',holdFor3Seconds:'உதவி அனுப்ப 3 வினாடி அழுத்து',releaseToCancel:'SOS ரத்து செய்ய விடு',helpDispatched:'உதவி அனுப்பப்பட்டது',authoritiesNotified:'அதிகாரிகளுக்குத் தெரிவிக்கப்பட்டது.',recentIncidents:'சமீபத்திய சம்பவங்கள்',viewMap:'வரைபடம் பார்',noDescription:'விவரம் இல்லை.',wardClear:'வார்டு தெளிவாக உள்ளது.',communityVitals:'சமூக நிலை',policePatrol:'காவல் ரோந்து',communityVerified:'சமூக சரிபார்ப்பு',streetLight:'தெரு விளக்கு கவரேஜ்',statusOperational:'நிலை: இயங்குகிறது',checkinDue:'செக்-இன் நிலுவை',loadingWardData:'வார்டு தரவு ஏற்றுகிறது...',
  zoneSafetyStatus:'மண்டல பாதுகாப்பு நிலை',businessZone:'வணிக மண்டலம்',dynamicScore:'இயங்கு மதிப்பெண்',footfallOverview:'நடமாட்ட கண்ணோட்டம்',realTimeTraffic:'நிகழ்நேர போக்குவரத்து',activeVisitors:'செயலில் பார்வையாளர்கள்',nearbyTourists:'அருகிலுள்ள சுற்றுலா பயணிகள்',radius200m:'200 மீ ஆரம்',verifiedTouristsInVicinity:'சரிபார்க்கப்பட்ட பயணிகள் அருகில்',safetyAdvisories:'பாதுகாப்பு ஆலோசனைகள்',postAdvisory:'ஆலோசனை பதிவிடு',noAdvisoryDetails:'ஆலோசனை விவரங்கள் இல்லை.',noActiveAdvisories:'செயலில் ஆலோசனைகள் இல்லை.',blockchainIdentityProof:'பிளாக்செயின் அடையாள சான்று',validateCredentials:'Trackmate லெட்ஜரில் சரிபார்க்கவும்.',verify:'சரிபார்',ledgerVerified:'லெட்ஜர் சரிபார்க்கப்பட்டது',authValid:'அங்கீகாரம் செல்லுபடி',securityClearance:'பாதுகாப்பு அனுமதி சரிபார்க்கப்பட்டது',verification:'சரிபார்ப்பு',identityProofed:'அடையாளம் நிரூபிக்கப்பட்டது',pending:'நிலுவையில்',role:'பங்கு',identityNotFound:'லெட்ஜரில் அடையாளம் இல்லை.',verificationUnavailable:'சரிபார்ப்பு சேவை கிடைக்கவில்லை.',
  holdForBusinessSOS:'வணிக SOS அழுத்து',holdFor3SecondsTrigger:'ரெட் அலாரம் 3 வினாடி அழுத்து',releaseToCancel2:'SOS ரத்து',sosDispatched:'SOS அதிகாரிகளுக்கு அனுப்பப்பட்டது',authorityReceived:'அதிகார குழு நிகழ்நேரத்தில் பெற்றது.',loadingBusinessData:'வணிக தரவு ஏற்றுகிறது...',
  commandDashboard:'கட்டளை டாஷ்போர்டு',authorityOfficer:'அதிகார அதிகாரி',liveUsers:'நேரடி பயனர்கள்',openIncidents:'திறந்த சம்பவங்கள்',sosLastHour:'SOS (கடைசி மணி)',totalProfiles:'மொத்த சுயவிவரங்கள்',needsAttention:'கவனம் தேவை',liveTrackingActive:'நேரடி கண்காணிப்பு செயலில்',authorityCommandMap:'அதிகார கட்டளை நேரடி வரைபடம்',trackingDevices:'கண்காணிப்பு',liveDevicesAcrossZones:'நேரடி சாதனங்கள் மண்டலங்களில்.',resetView:'காட்சி மீட்டமை',focusLive:'நேரடி கவனம்',drawZone:'மண்டலம் வரை',mapLegend:'வரைபட குறிப்பு',safeZone:'பாதுகாப்பான மண்டலம்',moderateZone:'மிதமான மண்டலம்',highRisk:'அதிக ஆபத்து',restrictedZone:'தடைசெய்யப்பட்ட மண்டலம்',tourist:'சுற்றுலா பயணி',resident:'குடியிருப்பாளர்',clearUserFilter:'வடிகட்டி அகற்று ✕',
  checkinToday:'இன்று',touristCheckins24h:'கடந்த 24 மணி செக்-இன்கள்',noCheckins24h:'24 மணியில் செக்-இன் இல்லை.',locationCheckin:'இருப்பிட செக்-இன்',checkedInStatus:'செக் இன் ஆனது',liveAlertFeed:'நேரடி எச்சரிக்கை ஊட்டம்',clickRowToIsolate:'வரைபடத்தில் அறிக்கையாளரை தனிமைப்படுத்த கிளிக் செய்யவும்',connectingToFeed:'ஊட்டத்துடன் இணைக்கிறது...',severityCol:'தீவிரம்',titleZone:'தலைப்பு / மண்டலம்',reporter:'அறிக்கையாளர்',status:'நிலை',actions:'செயல்கள்',unknownLocation:'அறியப்படாத இருப்பிடம்',system:'அமைப்பு',acknowledge:'ஏற்றுக்கொள்',resolve:'தீர்க்க',done:'✓ முடிந்தது',noActiveIncidents:'செயலில் சம்பவங்கள் இல்லை.',redAlert:'சிவப்பு எச்சரிக்கை',personInDanger:'ஆபத்தில் நபர்',unknownUser:'அறியப்படாத பயனர்',realDanger:'உண்மையான ஆபத்து',falseAlarm:'தவறான அலாரம்',confidence:'நம்பிக்கை',trackLocation:'இருப்பிடம் கண்காணி',zoneAdded:'மண்டலம் சேர்க்கப்பட்டது.',zoneDeleted:'மண்டலம் நீக்கப்பட்டது.',failedUpdateIncident:'சம்பவ புதுப்பிப்பு தோல்வி.',failedSaveZone:'மண்டலம் சேமிப்பு தோல்வி',failedDeleteZone:'மண்டலம் நீக்க தோல்வி.',deleteZoneConfirm:'இந்த மண்டலத்தை நீக்கவா?',reporterLocationUnavailable:'அறிக்கையாளர் இருப்பிடம் கிடைக்கவில்லை.',searchZonesPlaceholder:'மண்டலங்களைத் தேடு...',
};
export default ta;
