import type { TranslationKeys } from './en';
const te: TranslationKeys = {
  appName:'TRACKMATE',logout:'లాగ్ అవుట్',score:'స్కోర్',online:'ఆన్‌లైన్',refresh:'రిఫ్రెష్',save:'సేవ్',cancel:'రద్దు',submit:'సబ్మిట్',close:'మూసివేయి',loading:'లోడ్ అవుతోంది...',safe:'సురక్షితం',moderate:'మధ్యస్థం',restricted:'నిషేధిత',high:'ఎక్కువ',low:'తక్కువ',medium:'మధ్యస్థం',critical:'తీవ్రం',active:'సక్రియం',resolved:'పరిష్కరించబడింది',acknowledged:'అంగీకరించబడింది',unknown:'తెలియదు',language:'భాష',selectLanguage:'భాష ఎంచుకోండి',
  safetyScore:'భద్రతా స్కోర్',authorityNode:'అధికార నోడ్',navigation:'నావిగేషన్',dashboard:'డాష్‌బోర్డ్',incidents:'సంఘటనలు',userManagement:'వినియోగదారు నిర్వహణ',tourists:'పర్యాటకులు',residents:'నివాసితులు',businesses:'వ్యాపారాలు',tools:'సాధనాలు',dailyCheckins:'రోజువారీ చెక్-ఇన్',zoneManagement:'జోన్ నిర్వహణ',efirSystem:'ఈ-ఎఫ్ఐఆర్ వ్యవస్థ',safetyAnalytics:'భద్రతా విశ్లేషణ',sendAlert:'హెచ్చరిక పంపు',officer:'అధికారి',
  map:'మ్యాప్',trip:'ప్రయాణం',profile:'ప్రొఫైల్',local:'స్థానిక',feed:'ఫీడ్',report:'నివేదిక',intel:'సమాచారం',business:'వ్యాపారం',
  login:'లాగిన్',getStarted:'ప్రారంభించండి',unifiedSafetyPlatform:'ఏకీకృత భద్రతా ప్లాట్‌ఫారం v3',heroTitle:'రియల్-టైమ్ నగర భద్రతా సమాచారం',heroTitleHighlight:' నివాసితులు, సందర్శకులు మరియు ప్రతిస్పందన బృందాల కోసం',heroDescription:'TrackMate లైవ్ మ్యాప్‌లు, AI అసమానత గుర్తింపు మరియు అత్యవసర వర్క్‌ఫ్లోలను అనుసంధానం చేస్తుంది.',enterPlatform:'ప్లాట్‌ఫారంలో ప్రవేశించండి',alreadyHaveAccess:'ఇప్పటికే యాక్సెస్ ఉంది',selectAccessRole:'మీ పాత్ర ఎంచుకోండి',onePlatform:'ఒక ప్లాట్‌ఫారం, పాత్ర-నిర్దిష్ట వర్క్‌ఫ్లోలు',roleDescription:'సరైన సాధనాలను అన్‌లాక్ చేయడానికి మీ బాధ్యతలకు సరిపోయే పాత్రను ఉపయోగించండి.',continueAs:'గా కొనసాగించండి',coreCapabilities:'ప్రధాన సామర్థ్యాలు',coreCapabilitiesDesc:'ప్రజలు మరియు కమాండ్ బృందాల మధ్య వేగవంతమైన సమన్వయం కోసం.',footerBrand:'TrackMate పౌర భద్రతా ప్లాట్‌ఫారం',footerCopyright:'© 2026 TrackMate. అనుసంధానిత నగరాల కోసం సమన్వయ భద్రత.',
  touristLabel:'పర్యాటకుడు',residentLabel:'నివాసి',businessLabel:'వ్యాపారం',authorityLabel:'అధికారం',touristDesc:'రియల్-టైమ్ హెచ్చరికలు మరియు SOS మద్దతుతో ఆత్మవిశ్వాసంతో ప్రయాణించండి.',residentDesc:'తక్షణ సంఘటన నివేదనతో మీ పొరుగును రక్షించండి.',businessDesc:'AI ఉపయోగించి మీ ఆస్తి చుట్టూ ఉన్న ప్రమాదాన్ని పర్యవేక్షించండి.',authorityDesc:'కమాండ్ అనలిటిక్స్ మరియు ఈ-ఎఫ్ఐఆర్‌తో నగర భద్రతా కార్యకలాపాలను సమన్వయం చేయండి.',
  liveMonitoringGrid:'లైవ్ మానిటరింగ్ గ్రిడ్',liveMonitoringGridDesc:'కదలిక మరియు జోన్ ప్రమాదాన్ని ట్రాక్ చేయండి.',anomalyDetection:'అసమానత గుర్తింపు',anomalyDetectionDesc:'AI మోడళ్లు అసాధారణ నమూనాలను గుర్తిస్తాయి.',trustedIdentity:'విశ్వసనీయ గుర్తింపు',trustedIdentityDesc:'సురక్షిత ధృవీకరణ వర్క్‌ఫ్లోలు సరైన ప్రతిస్పందకులను నిర్ధారిస్తాయి.',
  systemProtected:'వ్యవస్థ రక్షిత — పర్యవేక్షణ సక్రియం',locationMonitored:'మీ స్థానం పర్యవేక్షించబడుతోంది',localAuthorities:'స్థానిక అధికారులు',liveSafetyGIS:'లైవ్ భద్రతా GIS',locateMe:'నన్ను కనుగొనండి',searchZones:'జోన్‌లు శోధించండి...',activeItinerary:'సక్రియ ప్రయాణ కార్యక్రమం',destination:'గమ్యస్థానం',duration:'వ్యవధి',updatePlan:'ప్రణాళిక నవీకరించండి',verifyStay:'బస ధృవీకరించు',noActiveTrip:'సక్రియ ప్రయాణం లేదు.',startPlanning:'ప్రణాళిక ప్రారంభించండి',safetyServices:'భద్రతా సేవలు',dailyCheckin:'రోజువారీ చెక్-ఇన్',checkedIn:'చెక్ ఇన్ అయింది ✓',reportAnomaly:'అసమానత నివేదించు',iotSync:'IoT సింక్',safeHouse:'సేఫ్ హౌస్',safetyBroadcasts:'భద్రతా ప్రసారాలు',allSectorsClear:'అన్ని రంగాలు క్లియర్. మీ ప్రయాణాన్ని ఆనందించండి!',holdSOS:'3 సెకన్లు నొక్కండి',alertSent:'హెచ్చరిక పంపబడింది',holding:'నొక్కుతోంది',redZoneNearby:'⚡ ఎరుపు జోన్ దగ్గరలో',
  fetchingLocation:'స్థానం పొందుతోంది...',locationUpdated:'స్థానం నవీకరించబడింది',locationDenied:'స్థాన ప్రాప్యత నిరాకరించబడింది',unableGetLocation:'స్థానం పొందలేకపోతోంది',checkinFailed:'చెక్-ఇన్ విఫలం.',dailyCheckinRecorded:'చెక్-ఇన్ నమోదైంది ✓',checkedInAt:'చెక్ ఇన్ అయింది',verificationFailed:'ధృవీకరణ విఫలం',youAreIn:'✓ మీరు ఉన్నారు',zone:'జోన్',notInAnyZone:'ℹ ఏ నమోదిత జోన్‌లో లేరు',noSafeZones:'సురక్షిత జోన్‌లు లేవు',nearestSafeZone:'సమీపంలోని సురక్షిత జోన్',sosTransmissionFailed:'SOS విఫలం!',anomalyReported:'అసమానత నివేదించబడింది',tripUpdated:'ప్రయాణం నవీకరించబడింది',
  reportSafetyAnomaly:'భద్రతా అసమానత నివేదిక',incidentType:'సంఘటన రకం',suspiciousActivity:'అనుమానాస్పద కార్యకలాపం',crimeTheft:'నేరం (దొంగతనం/వేధింపు)',medicalEmergency:'వైద్య అత్యవసరం',naturalDisaster:'ప్రకృతి విపత్తు',infrastructureHazard:'మౌలిక సదుపాయాల ప్రమాదం',accidentOther:'ప్రమాదం / ఇతర',title:'శీర్షిక',briefSummary:'సంక్షిప్త సారాంశం',description:'వివరణ',detailsPlaceholder:'వివరాలు...',severity:'తీవ్రత',autoDetected:'ఆటో-గుర్తింపు',submitReport:'నివేదిక సబ్మిట్',
  updateTravelPlan:'ప్రయాణ ప్రణాళిక నవీకరణ',destinationRegion:'గమ్యస్థాన ప్రాంతం',destinationPlaceholder:'ఉదా. తవాంగ్ జిల్లా',startDate:'ప్రారంభ తేదీ',endDate:'ముగింపు తేదీ',saveChanges:'మార్పులు సేవ్',
  iotDeviceSync:'IoT పరికర సింక్',bluetoothPair:'బ్లూటూత్ పెయిర్',searchBluetooth:'సమీపంలోని IoT బ్యాండ్‌లు శోధించు',searchingBluetooth:'బ్లూటూత్ శోధిస్తోంది...',wifiDirect:'వైఫై డైరెక్ట్',connectViaNetwork:'స్థానిక నెట్‌వర్క్ ద్వారా కనెక్ట్',wifiScanInitiated:'వైఫై స్కాన్ ప్రారంభమైంది',
  noWardAssigned:'మీ ఖాతాలో వార్డ్ లేదు.',yourArea:'మీ ప్రాంతం',liveMonitoring:'లైవ్ పర్యవేక్షణ',generalMonitoring:'సాధారణ పర్యవేక్షణ · అన్ని ప్రాంతాలు',healthy:'ఆరోగ్యకరం',activeCircle:'సక్రియ సర్కిల్',holdForEmergency:'అత్యవసరం కోసం నొక్కండి',holdFor3Seconds:'సహాయం పంపడానికి 3 సెకన్లు నొక్కండి',releaseToCancel:'SOS రద్దు చేయడానికి విడుదల',helpDispatched:'సహాయం పంపబడింది',authoritiesNotified:'అధికారులకు తెలియజేయబడింది.',recentIncidents:'ఇటీవలి సంఘటనలు',viewMap:'మ్యాప్ చూడు',noDescription:'వివరణ లేదు.',wardClear:'వార్డ్ క్లియర్.',communityVitals:'సమాజ స్థితి',policePatrol:'పోలీస్ గస్తీ',communityVerified:'సమాజ ధృవీకృతం',streetLight:'స్ట్రీట్ లైట్ కవరేజ్',statusOperational:'స్థితి: పనిచేస్తోంది',checkinDue:'చెక్-ఇన్ బాకీ',loadingWardData:'వార్డ్ డేటా లోడ్...',
  zoneSafetyStatus:'జోన్ భద్రతా స్థితి',businessZone:'వ్యాపార జోన్',dynamicScore:'డైనమిక్ స్కోర్',footfallOverview:'ఫుట్‌ఫాల్ అవలోకనం',realTimeTraffic:'రియల్-టైమ్ ట్రాఫిక్',activeVisitors:'సక్రియ సందర్శకులు',nearbyTourists:'సమీపంలోని పర్యాటకులు',radius200m:'200 మీ. వ్యాసార్ధం',verifiedTouristsInVicinity:'ధృవీకృత పర్యాటకులు సమీపంలో',safetyAdvisories:'భద్రతా సలహాలు',postAdvisory:'సలహా పోస్ట్',noAdvisoryDetails:'సలహా వివరాలు లేవు.',noActiveAdvisories:'సక్రియ సలహాలు లేవు.',blockchainIdentityProof:'బ్లాక్‌చెయిన్ గుర్తింపు రుజువు',validateCredentials:'Trackmate లెడ్జర్‌తో ధృవీకరించండి.',verify:'ధృవీకరించు',ledgerVerified:'లెడ్జర్ ధృవీకృతం',authValid:'ప్రమాణీకరణ చెల్లుబాటు',securityClearance:'భద్రతా అనుమతి ధృవీకృతం',verification:'ధృవీకరణ',identityProofed:'గుర్తింపు ప్రమాణీకృతం',pending:'పెండింగ్',role:'పాత్ర',identityNotFound:'లెడ్జర్‌లో గుర్తింపు లేదు.',verificationUnavailable:'ధృవీకరణ సేవ అందుబాటులో లేదు.',
  holdForBusinessSOS:'వ్యాపార SOS నొక్కండి',holdFor3SecondsTrigger:'రెడ్ అలారం 3 సెకన్లు నొక్కండి',releaseToCancel2:'SOS రద్దు',sosDispatched:'SOS అధికారులకు పంపబడింది',authorityReceived:'అధికార ప్యానెల్ ట్రిగర్ రియల్ టైమ్‌లో అందుకుంది.',loadingBusinessData:'వ్యాపార డేటా లోడ్...',
  commandDashboard:'కమాండ్ డాష్‌బోర్డ్',authorityOfficer:'అధికార అధికారి',liveUsers:'లైవ్ వినియోగదారులు',openIncidents:'తెరిచిన సంఘటనలు',sosLastHour:'SOS (చివరి గంట)',totalProfiles:'మొత్తం ప్రొఫైల్‌లు',needsAttention:'శ్రద్ధ అవసరం',liveTrackingActive:'లైవ్ ట్రాకింగ్ సక్రియం',authorityCommandMap:'అధికార కమాండ్ లైవ్ మ్యాప్',trackingDevices:'ట్రాకింగ్',liveDevicesAcrossZones:'లైవ్ పరికరాలు జోన్‌లలో.',resetView:'వ్యూ రీసెట్',focusLive:'లైవ్ ఫోకస్',drawZone:'జోన్ గీయు',mapLegend:'మ్యాప్ లెజెండ్',safeZone:'సురక్షిత జోన్',moderateZone:'మధ్యస్థ జోన్',highRisk:'ఎక్కువ ప్రమాదం',restrictedZone:'నిషేధిత జోన్',tourist:'పర్యాటకుడు',resident:'నివాసి',clearUserFilter:'ఫిల్టర్ తొలగించు ✕',
  checkinToday:'ఈరోజు',touristCheckins24h:'గత 24 గంటల చెక్-ఇన్‌లు',noCheckins24h:'24 గంటల్లో చెక్-ఇన్‌లు లేవు.',locationCheckin:'స్థాన చెక్-ఇన్',checkedInStatus:'చెక్ ఇన్ అయింది',liveAlertFeed:'లైవ్ హెచ్చరిక ఫీడ్',clickRowToIsolate:'మ్యాప్‌లో రిపోర్టర్‌ను వేరుచేయడానికి క్లిక్ చేయండి',connectingToFeed:'ఫీడ్‌కు కనెక్ట్ అవుతోంది...',severityCol:'తీవ్రత',titleZone:'శీర్షిక / జోన్',reporter:'రిపోర్టర్',status:'స్థితి',actions:'చర్యలు',unknownLocation:'తెలియని స్థానం',system:'వ్యవస్థ',acknowledge:'అంగీకరించు',resolve:'పరిష్కరించు',done:'✓ పూర్తి',noActiveIncidents:'సక్రియ సంఘటనలు లేవు.',redAlert:'రెడ్ అలర్ట్',personInDanger:'ప్రమాదంలో వ్యక్తి',unknownUser:'తెలియని వినియోగదారు',realDanger:'నిజమైన ప్రమాదం',falseAlarm:'తప్పుడు అలారం',confidence:'విశ్వాసం',trackLocation:'స్థానం ట్రాక్',zoneAdded:'జోన్ జోడించబడింది.',zoneDeleted:'జోన్ తొలగించబడింది.',failedUpdateIncident:'సంఘటన నవీకరణ విఫలం.',failedSaveZone:'జోన్ సేవ్ విఫలం',failedDeleteZone:'జోన్ తొలగింపు విఫలం.',deleteZoneConfirm:'ఈ జోన్ తొలగించాలా?',reporterLocationUnavailable:'రిపోర్టర్ స్థానం అందుబాటులో లేదు.',searchZonesPlaceholder:'జోన్‌లు శోధించండి...',
};
export default te;
