import type { TranslationKeys } from './en';
const ur: Partial<TranslationKeys> = {
  appName:'TRACKMATE',logout:'لاگ آؤٹ',score:'اسکور',online:'آن لائن',refresh:'ریفریش',save:'محفوظ کریں',cancel:'منسوخ',submit:'جمع کریں',close:'بند کریں',loading:'لوڈ ہو رہا ہے...',safe:'محفوظ',moderate:'معتدل',restricted:'ممنوع',high:'زیادہ',low:'کم',medium:'درمیانہ',critical:'سنگین',active:'فعال',resolved:'حل ہو گیا',acknowledged:'تسلیم شدہ',unknown:'نامعلوم',language:'زبان',selectLanguage:'زبان منتخب کریں',
  safetyScore:'حفاظتی اسکور',authorityNode:'اتھارٹی نوڈ',navigation:'نیویگیشن',dashboard:'ڈیش بورڈ',incidents:'واقعات',userManagement:'صارف انتظام',tourists:'سیاح',residents:'مقامی باشندے',businesses:'کاروبار',tools:'ٹولز',dailyCheckins:'روزانہ چیک ان',zoneManagement:'زون انتظام',efirSystem:'ای ایف آئی آر نظام',safetyAnalytics:'حفاظتی تجزیات',sendAlert:'الرٹ بھیجیں',officer:'افسر',
  map:'نقشہ',trip:'سفر',profile:'پروفائل',local:'مقامی',feed:'فیڈ',report:'رپورٹ',intel:'معلومات',business:'کاروبار',
  login:'لاگ ان',getStarted:'شروع کریں',unifiedSafetyPlatform:'متحدہ حفاظتی پلیٹ فارم v3',heroTitle:'ریئل ٹائم شہری حفاظتی معلومات',heroTitleHighlight:' مقامی، مہمان اور رسپانس ٹیموں کے لیے',heroDescription:'TrackMate لائیو نقشے، AI بے ضابطگی کا پتہ اور ایمرجنسی ورک فلو کو جوڑتا ہے۔',enterPlatform:'پلیٹ فارم میں داخل ہوں',alreadyHaveAccess:'پہلے سے رسائی ہے',selectAccessRole:'اپنا کردار منتخب کریں',onePlatform:'ایک پلیٹ فارم، کردار مخصوص ورک فلو',roleDescription:'صحیح ٹولز انلاک کرنے کے لیے اپنی ذمہ داریوں سے ملتا کردار استعمال کریں۔',continueAs:'کے طور پر جاری رکھیں',coreCapabilities:'بنیادی صلاحیتیں',coreCapabilitiesDesc:'عوامی صارفین اور کمانڈ ٹیموں کے درمیان تیز رفتار ہم آہنگی۔',footerBrand:'TrackMate شہری حفاظتی پلیٹ فارم',footerCopyright:'© 2026 TrackMate۔ جڑے ہوئے شہروں کے لیے۔',
  touristLabel:'سیاح',residentLabel:'مقامی باشندہ',businessLabel:'کاروبار',authorityLabel:'اتھارٹی',touristDesc:'ریئل ٹائم الرٹس اور SOS سپورٹ کے ساتھ اعتماد سے سفر کریں۔',residentDesc:'فوری واقعہ رپورٹنگ سے اپنے علاقے کی حفاظت کریں۔',businessDesc:'AI استعمال کر کے اپنی جائیداد کے اردگرد خطرے کی نگرانی کریں۔',authorityDesc:'کمانڈ تجزیات اور ای ایف آئی آر سے شہری حفاظتی آپریشنز کو مربوط کریں۔',
  liveMonitoringGrid:'لائیو مانیٹرنگ گرڈ',liveMonitoringGridDesc:'حرکت اور زون خطرے کو ٹریک کریں۔',anomalyDetection:'بے ضابطگی کا پتہ',anomalyDetectionDesc:'AI ماڈلز غیر معمولی پیٹرن شناخت کرتے ہیں۔',trustedIdentity:'قابل اعتماد شناخت',trustedIdentityDesc:'محفوظ تصدیقی ورک فلو صحیح جواب دہندگان کو یقینی بناتے ہیں۔',
  systemProtected:'نظام محفوظ — نگرانی فعال',locationMonitored:'آپ کا مقام نگرانی میں ہے',localAuthorities:'مقامی حکام',liveSafetyGIS:'لائیو حفاظتی GIS',locateMe:'مجھے تلاش کریں',searchZones:'زون تلاش کریں...',activeItinerary:'فعال سفری پروگرام',destination:'منزل',duration:'مدت',updatePlan:'منصوبہ اپڈیٹ',verifyStay:'قیام تصدیق',noActiveTrip:'کوئی فعال سفر نہیں۔',startPlanning:'منصوبہ بندی شروع کریں',safetyServices:'حفاظتی خدمات',dailyCheckin:'روزانہ چیک ان',checkedIn:'چیک ان ہو گیا ✓',reportAnomaly:'بے ضابطگی رپورٹ',iotSync:'IoT سنک',safeHouse:'محفوظ گھر',safetyBroadcasts:'حفاظتی نشریات',allSectorsClear:'تمام سیکٹر صاف۔ اپنے سفر سے لطف اٹھائیں!',holdSOS:'3 سیکنڈ دبائیں',alertSent:'الرٹ بھیج دیا',holding:'دبایا ہوا',redZoneNearby:'⚡ سرخ زون قریب',
  fetchingLocation:'مقام حاصل کر رہا ہے...',locationUpdated:'مقام اپڈیٹ ہوا',locationDenied:'مقام تک رسائی انکار',unableGetLocation:'مقام حاصل کرنے سے قاصر',checkinFailed:'چیک ان ناکام۔',dailyCheckinRecorded:'روزانہ چیک ان درج ✓',checkedInAt:'چیک ان ہوا',verificationFailed:'تصدیق ناکام',youAreIn:'✓ آپ ہیں',zone:'زون',notInAnyZone:'ℹ کسی رجسٹرڈ زون میں نہیں',noSafeZones:'محفوظ زون نہیں',nearestSafeZone:'قریب ترین محفوظ زون',sosTransmissionFailed:'SOS ناکام!',anomalyReported:'بے ضابطگی رپورٹ ہوئی',tripUpdated:'سفر اپڈیٹ ہوا',
  reportSafetyAnomaly:'حفاظتی بے ضابطگی رپورٹ',incidentType:'واقعے کی قسم',suspiciousActivity:'مشکوک سرگرمی',crimeTheft:'جرم (چوری/ہراساں)',medicalEmergency:'طبی ایمرجنسی',naturalDisaster:'قدرتی آفت',infrastructureHazard:'بنیادی ڈھانچے کا خطرہ',accidentOther:'حادثہ / دیگر',title:'عنوان',briefSummary:'مختصر خلاصہ',description:'تفصیل',detailsPlaceholder:'تفصیلات...',severity:'شدت',autoDetected:'خودکار شناخت',submitReport:'رپورٹ جمع کریں',
  updateTravelPlan:'سفری منصوبہ اپڈیٹ',destinationRegion:'منزل کا علاقہ',destinationPlaceholder:'مثلاً توانگ ضلع',startDate:'شروع تاریخ',endDate:'اختتام تاریخ',saveChanges:'تبدیلیاں محفوظ',
  iotDeviceSync:'IoT ڈیوائس سنک',bluetoothPair:'بلوٹوتھ پیئر',searchBluetooth:'قریبی IoT بینڈ تلاش',searchingBluetooth:'بلوٹوتھ تلاش ہو رہا ہے...',wifiDirect:'وائی فائی ڈائریکٹ',connectViaNetwork:'مقامی نیٹ ورک سے جوڑیں',wifiScanInitiated:'وائی فائی اسکین شروع',
  noWardAssigned:'آپ کے اکاؤنٹ میں کوئی وارڈ نہیں۔',yourArea:'آپ کا علاقہ',liveMonitoring:'لائیو نگرانی',generalMonitoring:'عمومی نگرانی · تمام علاقے',healthy:'صحت مند',activeCircle:'فعال حلقہ',holdForEmergency:'ایمرجنسی کے لیے دبائیں',holdFor3Seconds:'مدد بھیجنے 3 سیکنڈ دبائیں',releaseToCancel:'SOS منسوخ کرنے چھوڑیں',helpDispatched:'مدد بھیج دی گئی',authoritiesNotified:'حکام کو مطلع کیا گیا۔',recentIncidents:'حالیہ واقعات',viewMap:'نقشہ دیکھیں',noDescription:'تفصیل نہیں۔',wardClear:'وارڈ صاف ہے۔',communityVitals:'کمیونٹی حالت',policePatrol:'پولیس گشت',communityVerified:'کمیونٹی تصدیق شدہ',streetLight:'اسٹریٹ لائٹ کوریج',statusOperational:'حالت: فعال',checkinDue:'چیک ان باقی',loadingWardData:'وارڈ ڈیٹا لوڈ...',
  zoneSafetyStatus:'زون حفاظتی حالت',businessZone:'کاروباری زون',dynamicScore:'متحرک اسکور',footfallOverview:'فٹ فال جائزہ',realTimeTraffic:'ریئل ٹائم ٹریفک',activeVisitors:'فعال زائرین',nearbyTourists:'قریبی سیاح',radius200m:'200 میٹر دائرہ',verifiedTouristsInVicinity:'تصدیق شدہ سیاح آس پاس',safetyAdvisories:'حفاظتی مشورے',postAdvisory:'مشورہ پوسٹ',noAdvisoryDetails:'مشورے کی تفصیلات نہیں۔',noActiveAdvisories:'فعال مشورے نہیں۔',blockchainIdentityProof:'بلاکچین شناختی ثبوت',validateCredentials:'Trackmate لیجر سے تصدیق کریں۔',verify:'تصدیق',ledgerVerified:'لیجر تصدیق شدہ',authValid:'تصدیق درست',securityClearance:'حفاظتی اجازت تصدیق شدہ',verification:'تصدیق',identityProofed:'شناخت ثابت',pending:'زیر التوا',role:'کردار',identityNotFound:'لیجر میں شناخت نہیں۔',verificationUnavailable:'تصدیقی سروس دستیاب نہیں۔',
  holdForBusinessSOS:'کاروباری SOS دبائیں',holdFor3SecondsTrigger:'ریڈ الارم 3 سیکنڈ دبائیں',releaseToCancel2:'SOS منسوخ',sosDispatched:'SOS حکام کو بھیجا گیا',authorityReceived:'اتھارٹی پینل نے ریئل ٹائم میں وصول کیا۔',loadingBusinessData:'کاروباری ڈیٹا لوڈ...',
  commandDashboard:'کمانڈ ڈیش بورڈ',authorityOfficer:'اتھارٹی افسر',liveUsers:'لائیو صارفین',openIncidents:'کھلے واقعات',sosLastHour:'SOS (آخری گھنٹہ)',totalProfiles:'کل پروفائلز',needsAttention:'توجہ ضروری',liveTrackingActive:'لائیو ٹریکنگ فعال',authorityCommandMap:'اتھارٹی کمانڈ لائیو نقشہ',trackingDevices:'ٹریکنگ',liveDevicesAcrossZones:'لائیو ڈیوائسز زونز میں۔',resetView:'ویو ری سیٹ',focusLive:'لائیو فوکس',drawZone:'زون بنائیں',mapLegend:'نقشے کی علامت',safeZone:'محفوظ زون',moderateZone:'معتدل زون',highRisk:'زیادہ خطرہ',restrictedZone:'ممنوع زون',tourist:'سیاح',resident:'مقامی باشندہ',clearUserFilter:'فلٹر ہٹائیں ✕',
  checkinToday:'آج',touristCheckins24h:'آخری 24 گھنٹے چیک ان',noCheckins24h:'24 گھنٹوں میں کوئی چیک ان نہیں۔',locationCheckin:'مقام چیک ان',checkedInStatus:'چیک ان ہوا',liveAlertFeed:'لائیو الرٹ فیڈ',clickRowToIsolate:'نقشے پر رپورٹر کو الگ کرنے کلک کریں',connectingToFeed:'فیڈ سے جڑ رہا ہے...',severityCol:'شدت',titleZone:'عنوان / زون',reporter:'رپورٹر',status:'حالت',actions:'اقدامات',unknownLocation:'نامعلوم مقام',system:'نظام',acknowledge:'تسلیم',resolve:'حل کریں',done:'✓ مکمل',noActiveIncidents:'فعال واقعات نہیں۔',redAlert:'ریڈ الرٹ',personInDanger:'خطرے میں شخص',unknownUser:'نامعلوم صارف',realDanger:'حقیقی خطرہ',falseAlarm:'غلط الارم',confidence:'اعتماد',trackLocation:'مقام ٹریک',zoneAdded:'زون شامل ہوا۔',zoneDeleted:'زون ہٹا دیا۔',failedUpdateIncident:'واقعہ اپڈیٹ ناکام۔',failedSaveZone:'زون محفوظ ناکام',failedDeleteZone:'زون ہٹانا ناکام۔',deleteZoneConfirm:'یہ زون ہٹائیں؟',reporterLocationUnavailable:'رپورٹر کا مقام دستیاب نہیں۔',searchZonesPlaceholder:'زون تلاش...',
};
export default ur;
